Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2020-05, with the labels that each got.

#887 Tandem URL placeholder
  src/actions/results.js
Labels: dual merge, pause merge

#886 Update/save export tandem hide
  src/Components/ResultsContainer/ResultsContainer.jsx
  src/Components/ResultsControls/ResultsControls.jsx
Labels: pause merge

#894 Hook results card into the tandem number
  src/Components/ResultsCard/ResultsCard.jsx
Labels: dual merge

#901 Add unaccompanied status filter
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
  src/reducers/filters/filters.js
Labels: dual merge

#918 Tandem CSV export
  src/Components/ResultsControls/ResultsControls.jsx
  src/Components/SearchResultsExportLink/SearchResultsExportLink.jsx
  src/actions/results.js
Labels: dual merge
