Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2021-08, with the labels that each got.

#1549 Chore/typescript
  .eslintrc
  config/paths.js
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  config/webpackDevServer.config.js
  package.json
  src/Components/Alert/Alert.tsx
  src/Components/BidTracker/ContactCDOButton/__snapshots__/ContactCDOButton.test.jsx.snap
  src/Components/BidTracker/OverlayAlert/TimeRemaining/TimeRemaining.tsx
  src/Components/Differentials/__snapshots__/Differentials.test.jsx.snap
  src/Components/HomePageBanner/__snapshots__/HomePageBanner.test.jsx.snap
  src/Components/LinkButton/LinkButton.jsx
  src/Components/LinkButton/LinkButton.tsx
  src/Components/LinkButton/index.ts
  src/Components/MediaQuery/MediaQuery.jsx
  src/Components/MediaQuery/MediaQuery.tsx
  src/Components/Notifications/NotificationRow/__snapshots__/NotificationRow.test.jsx.snap
  src/Components/OBCUrl/OBCUrl.tsx
  src/Components/OBCUrl/__snapshots__/OBCUrl.test.jsx.snap
  src/Components/ProfileDashboard/Favorites/FavoritesListResultsCard/__snapshots__/FavoritesListResultsCard.test.jsx.snap
  src/Components/ViewDetailsButton/__snapshots__/ViewDetailsButton.test.jsx.snap
  tsconfig.json
  yarn.lock
Labels: aging :older_adult:

#1665 classifications for private profile
  src/Components/BidderPortfolio/CheckboxList/CheckboxList.jsx
  src/Components/BidderPortfolio/ClientBadge/ClientBadge.jsx
  src/Components/Glossary/Glossary.jsx
  src/Components/GlossaryTermTrigger/GlossaryTermTrigger.jsx
  src/Components/ProfileDashboard/Classifications/Classifications.jsx
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Constants/Classifications.js
  src/Constants/PropTypes.js
  src/Containers/Dashboard/Dashboard.jsx
  src/actions/classifications.js
  src/actions/userProfile.js
  src/reducers/classifications/classifications.js
  src/reducers/classifications/index.js
  src/sass/_bidderPortfolio.scss
  src/sass/_profile.scss
  src/utilities.js
Labels: dual merge

#1727 Add download link for Glossary
  config/webpack.config.prod.js
  package.json
  src/Components/Glossary/Glossary.jsx
  src/Components/Glossary/GlossaryExport/GlossaryExport.tsx
  src/Components/Glossary/GlossaryExport/index.tsx
  src/Components/Glossary/__snapshots__/Glossary.test.jsx.snap
  src/sass/_glossary.scss
  yarn.lock
Labels: Release

#1724 Update wording to reflect one accepted handshake per cycle
  src/Components/BidTracker/OverlayAlert/HandshakeOfferedAlert/HandshakeOfferedAlert.jsx
  src/sass/_bidTracker.scss
Labels: Release

#1627 re-added org dropdown
  .eslintrc
  public/config/config.json
  public/config/config_dev.json
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/BureauResultsCard/BureauResultsCard.jsx
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/BureauPage/PositionManager/PositionManager.test.jsx
  src/Components/PostPage/Dashboard/Dashboard.jsx
  src/Components/PostPage/Dashboard/Dashboard.test.jsx
  src/Components/PostPage/Dashboard/index.js
  src/Components/PostPage/PostPage.jsx
  src/Components/PostPage/PostPage.test.jsx
  src/Components/PostPage/PostPageLoadable.jsx
  src/Components/PostPage/index.js
  src/Components/ProfileMenu/ProfileMenuCollapsed/__snapshots__/ProfileMenuCollapsed.test.jsx.snap
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/ProfilePage/ProfilePage.jsx
  src/Constants/EndpointParams.js
  src/Constants/Menu.js
  src/Containers/Bureau/Bureau.jsx
  src/Containers/Post/Post.jsx
  src/Containers/Post/Post.test.jsx
  src/Containers/Post/index.js
  src/actions/bureauPositions.js
  src/actions/bureauPositions.test.js
  src/reducers/filters/filters.js
Labels: Release
