Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2021-12, with the labels that each got.

#1859 fix for public condensed bid tracker TM-2416
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Containers/ProfilePublic/ProfilePublic.jsx
  src/Containers/ProfilePublic/ProfilePublic.test.jsx
Labels: do not merge

#1882 Feature/search sort user roles TM-2423
  src/Components/AdministratorPage/UserRoles/UserRoles.jsx
  src/Components/AdministratorPage/UserRoles/UserRoles.test.jsx
  src/Components/AdministratorPage/UserRoles/UserRow/UserRow.jsx
  src/Components/AdministratorPage/UserRoles/UserRow/__snapshots__/UserRow.test.jsx.snap
  src/Components/Form/Form.test.jsx
  src/Components/GlossaryEditor/GlossaryEditorCard/GlossaryEditorCard.test.jsx
  src/actions/userRoles.js
  src/sass/_administrator.scss
Labels: dual merge

#1883 adding submit & help link to tutorial
  public/assets/img/add_to_bid_list.gif
  public/assets/img/submit_bid.gif
  src/Components/Footer/Footer.jsx
  src/Components/Footer/__snapshots__/Footer.test.jsx.snap
  src/Components/ResultsPage/ResultsPage.jsx
  src/Components/ResultsPage/tutorialSteps.js
Labels: do not merge

#1892 Agenda Item History integration
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemHistory/__snapshots__/AgendaItemHistory.test.jsx.snap
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.test.jsx
  src/Components/Agenda/RemarksPill/__snapshots__/RemarksPill.test.jsx.snap
  src/Constants/Sort.js
  src/Containers/Dashboard/Dashboard.jsx
  src/actions/agendaItemHistory.js
  src/actions/client.js
  src/actions/client.test.js
  src/hooks.js
  src/reducers/agendaItemHistory/agendaItemHistory.js
  src/reducers/agendaItemHistory/index.js
  src/reducers/index.js
  src/sass/_agenda.scss
Labels: WIP, dual merge

#1893 agenda item history export
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/actions/agendaItemHistory.js
Labels: WIP, dual merge

#1887 Put employee profile report in a modal using react-pdf-viewer
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  package.json
  public/config/config.json
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileModal.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
  src/utilities.js
  yarn.lock
Labels: WIP
