Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2021-07, with the labels that each got.

#1588 try/catch commit hash
  config/webpack.config.prod.js
Labels: Release

#1531 overlay hs registered by another client
  src/Components/BidTracker/BidHelpers.js
  src/Components/BidTracker/BidHelpers.test.js
  src/Components/BidTracker/BidStep/BidStepIcon/BidStepIcon.jsx
  src/Components/BidTracker/BidStep/BidSteps.jsx
  src/Components/BidTracker/BidStep/__snapshots__/BidSteps.test.jsx.snap
  src/Components/BidTracker/BidTrackerCard/BidTrackerCard.jsx
  src/Components/BidTracker/BidTrackerCard/__snapshots__/BidTrackerCard.test.jsx.snap
  src/Components/BidTracker/BidTrackerCardContainer/__snapshots__/BidTrackerCardContainer.test.jsx.snap
  src/Components/BidTracker/BidTrackerCardList/__snapshots__/BidTrackerCardList.test.jsx.snap
  src/Components/BidTracker/BidTrackerCardTop/__snapshots__/BidTrackerCardTop.test.jsx.snap
  src/Components/BidTracker/OverlayAlert/HandshakeRegisterAnotherClientAlert/HandshakeRegisterAnotherClientAlert.jsx
  src/Components/BidTracker/OverlayAlert/HandshakeRegisterAnotherClientAlert/HandshakeRegisterAnotherClientAlert.test.jsx
  src/Components/BidTracker/OverlayAlert/HandshakeRegisterAnotherClientAlert/__snapshots__/HandshakeRegisterAnotherClientAlert.test.jsx.snap
  src/Components/BidTracker/OverlayAlert/HandshakeRegisterAnotherClientAlert/index.js
  src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
  src/Components/BidTracker/OverlayAlert/__snapshots__/OverlayAlert.test.jsx.snap
  src/Components/BidTracker/PriorityCards/IsOnStandby/__snapshots__/IsOnStandby.test.jsx.snap
  src/Components/BidTracker/__snapshots__/BidTracker.test.jsx.snap
  src/Components/FavoritePositions/__snapshots__/FavoritePositions.test.jsx.snap
  src/Components/HomePagePositions/__snapshots__/HomePagePositions.test.jsx.snap
  src/Components/HomePagePositionsList/__snapshots__/HomePagePositionsList.test.jsx.snap
  src/Components/HomePagePositionsSection/__snapshots__/HomePagePositionsSection.test.jsx.snap
  src/Components/ProfileDashboard/BidList/__snapshots__/BidList.test.jsx.snap
  src/Components/ResultsCondensedCard/__snapshots__/ResultsCondensedCard.test.jsx.snap
  src/__mocks__/bidListObject.js
  src/sass/_bidTracker.scss
  src/sass/_variables.scss
Labels: Release

#1589 updating text from post to location
  src/Components/BureauPage/BidderRankings/BidderRankings.jsx
Labels: Release

#1592 fix ribbon spacing for smaller results cards
  src/sass/_ribbon.scss
Labels: Release

#1573 Updating HS Notifications
  public/assets/img/handshake-closed.svg
  src/Components/About/Content/__snapshots__/Content.test.jsx.snap
  src/Components/Alert/Alert.tsx
  src/Components/Alert/__snapshots__/Alert.test.jsx.snap
  src/Components/BidTracker/Messages/HandshakeRevoked.jsx
  src/Components/BidderPortfolio/BidderPortfolioContainer/__snapshots__/BidderPortfolioContainer.test.jsx.snap
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/CandidateManager/CandidateManager.jsx
  src/Components/BureauPage/CandidateManager/index.js
  src/Components/BureauPage/CandidateManagerTable/CandidateManagerTable.jsx
  src/Components/BureauPage/CandidateManagerTable/index.js
  src/Components/GlossaryEditor/GlossaryEditorCardList/__snapshots__/GlossaryEditorCardList.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorPageHeader/__snapshots__/GlossaryEditorPageHeader.test.jsx.snap
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/SaveNewSearchAlert/__snapshots__/SaveNewSearchAlert.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/Containers/Toast/Toast.jsx
  src/actions/handshake.js
  src/actions/notifications.js
  src/actions/toast.js
  src/reducers/handshake/handshake.js
  src/reducers/handshake/index.js
  src/reducers/toast/toast.js
  src/sass/_candidateManager.scss
  src/sass/_toast.scss
  src/sass/_tooltip.scss
  src/sass/styles.scss
Labels: Release

#1590 position -> position_info
  src/Components/BureauPage/BidderRankings/BidderRankings.jsx
Labels: Release

#1593 bidtracker updates
  src/Components/BidTracker/BidTrackerCard/BidTrackerCard.jsx
  src/Components/BidTracker/BidTrackerCard/__snapshots__/BidTrackerCard.test.jsx.snap
  src/Components/BidTracker/BidTrackerCardTop/BidTrackerCardTop.jsx
  src/Components/BidTracker/OverlayAlert/HandshakeOfferedAlert/HandshakeOfferedAlert.jsx
  src/Components/BidTracker/PriorityCards/IsOnStandby/__snapshots__/IsOnStandby.test.jsx.snap
Labels: Release

#1576 Feature/bureau hs modal
  config/jest/setupTests.js
  package.json
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/BureauPage/PositionManagerBidders/PositionManagerBidders.jsx
  src/Components/BureauPage/PositionManagerDetails/PositionManagerDetails.jsx
  src/Components/Handshake/EditHandshake/EditHandshake.jsx
  src/Components/Handshake/EditHandshake/EditHandshakeLoadable.jsx
  src/Components/Handshake/EditHandshake/index.js
  src/Components/Handshake/HandshakeBureauButton/HandshakeBureauButton.jsx
  src/Containers/DarkMode/DarkMode.test.jsx
  src/actions/handshake.js
  src/sass/_bureau.scss
  src/sass/_handshakeModal.scss
  src/sass/_ribbon.scss
  src/sass/styles.scss
  src/utilities.js
  yarn.lock
Labels: Release

#1605 fix spacing
  src/sass/_bureau.scss
Labels: Release

#1607 Changing className var keyword
  src/Components/About/Content/__snapshots__/Content.test.jsx.snap
  src/Components/Alert/Alert.tsx
  src/Components/BidderPortfolio/BidderPortfolioContainer/__snapshots__/BidderPortfolioContainer.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorCardList/__snapshots__/GlossaryEditorCardList.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorPageHeader/__snapshots__/GlossaryEditorPageHeader.test.jsx.snap
  src/Components/SaveNewSearchAlert/__snapshots__/SaveNewSearchAlert.test.jsx.snap
  src/Containers/Toast/Toast.jsx
  src/actions/handshake.js
  src/actions/toast.js
  src/reducers/toast/toast.js
Labels: Release

#1597 showing panel notification on overlay collapse
  src/Components/BidTracker/BidStep/BidSteps.jsx
  src/Components/BidTracker/BidTrackerCard/BidTrackerCard.jsx
  src/Components/BidTracker/BidTrackerCard/__snapshots__/BidTrackerCard.test.jsx.snap
  src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
Labels: Release

#1609 to bool
  src/Components/About/Content/__snapshots__/Content.test.jsx.snap
  src/Components/Alert/Alert.tsx
  src/Components/Alert/__snapshots__/Alert.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioContainer/__snapshots__/BidderPortfolioContainer.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorCardList/__snapshots__/GlossaryEditorCardList.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorPageHeader/__snapshots__/GlossaryEditorPageHeader.test.jsx.snap
  src/Components/SaveNewSearchAlert/__snapshots__/SaveNewSearchAlert.test.jsx.snap
  src/Containers/Toast/Toast.jsx
  src/actions/notifications.js
  src/reducers/toast/toast.js
Labels: Release

#1608 Fix revoke after expiration TM-2281
  src/Components/Handshake/EditHandshake/EditHandshake.jsx
  src/Components/Handshake/HandshakeBureauButton/HandshakeBureauButton.jsx
Labels: Release

#1615 direct point to tsx and reverting hacks
  src/Components/About/Content/__snapshots__/Content.test.jsx.snap
  src/Components/Alert/Alert.tsx
  src/Components/Alert/__snapshots__/Alert.test.jsx.snap
  src/Components/Alert/index.js
  src/Components/BidderPortfolio/BidderPortfolioContainer/__snapshots__/BidderPortfolioContainer.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorCardList/__snapshots__/GlossaryEditorCardList.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorPageHeader/__snapshots__/GlossaryEditorPageHeader.test.jsx.snap
  src/Components/SaveNewSearchAlert/__snapshots__/SaveNewSearchAlert.test.jsx.snap
  src/Containers/Toast/Toast.jsx
  src/actions/handshake.js
  src/actions/notifications.js
  src/actions/toast.js
  src/reducers/toast/toast.js
  src/sass/_toast.scss
Labels: Release

#1614 Fix logic for hiding/showing tooltip
  src/Components/BidTracker/BidTrackerCard/BidTrackerCard.jsx
  src/Components/BidTracker/BidTrackerCard/__snapshots__/BidTrackerCard.test.jsx.snap
  src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
Labels: Release

#1606 Update/add hs tooltips TM-2280 TM-2277
  src/Components/Handshake/HandshakeStatus/HandshakeStatus.jsx
  src/sass/_handshakeModal.scss
  src/sass/_handshakeStatus.scss
  src/sass/_variables.scss
Labels: Release

#1616 Historical HS vs New HS fix TM-2282
  src/Components/Handshake/EditHandshake/EditHandshake.jsx
  src/Components/Handshake/HandshakeBureauButton/HandshakeBureauButton.jsx
Labels: Release

#1618 add required param on refresh
  src/Components/Handshake/EditHandshake/EditHandshake.jsx
  src/actions/availableBidders.js
  src/actions/availableBidders.test.js
Labels: Release

#1619 Fix/rework hs edge cases
  src/Components/Handshake/EditHandshake/EditHandshake.jsx
  src/Constants/PropTypes.js
Labels: Release, dual merge

#1635 garbage collect to avoid memory issues in circleci
  config/jest/setupTests.js
  package.json
Labels: do not merge
