Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2021-11, with the labels that each got.

#1716 HS Registered Animation TM-2264
  src/Components/BidTracker/BidPhaseConfig/Complete.js
  src/Components/BidTracker/BidStep/BidSteps.jsx
  src/Components/BidTracker/BidStep/BidSteps.test.jsx
  src/Components/BidTracker/BidStep/HandshakeAnimation.jsx
  src/Components/BidTracker/BidStep/HandshakeAnimation.test.jsx
  src/Components/BidTracker/BidStep/__snapshots__/HandshakeAnimation.test.jsx.snap
  src/Components/BureauPage/BureauResultsCard/BureauResultsCard.jsx
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/BureauPage/PositionManagerBidders/PositionManagerBidders.jsx
  src/Components/BureauPage/PositionManagerDetails/PositionManagerDetails.jsx
  src/Components/Handshake/HandshakeStatus/HandshakeStatus.jsx
  src/sass/_bidTracker.scss
  src/sass/_bureau.scss
Labels: Release

#1827 storing sort in saved search TM-2372
  src/Constants/EndpointParams.js
Labels: Release

#1828 changing about text to help TM-524
  src/Components/About/About.jsx
  src/Components/AdministratorPage/Dashboard/Dashboard.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Footer/__snapshots__/Footer.test.jsx.snap
  src/routes.js
Labels: Release

#1830 from calc to static TM-2388
  src/sass/_ribbon.scss
Labels: Release

#1826 Change default sort to -posted date TM-2376
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
  src/Constants/Sort.js
Labels: Release

#1833 Reset htf on PV selection
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.test.jsx
Labels: bug, Release

#1785 registered date added to HS status tooltip
  src/Components/BureauPage/PositionManagerBidders/PositionManagerBidders.jsx
  src/Components/Handshake/HandshakeStatus/HandshakeStatus.jsx
  src/sass/_handshakeStatus.scss
Labels: dual merge, Release

#1752 expanding available bidders chart stats
  src/Components/AvailableBidder/AvailableBidderStats/AvailableBidderStats.jsx
  src/sass/_availableBidders.scss
  src/utilities.js
Labels: dual merge
