Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-04, with the labels that each got.

#2058 Chore/8.1.1
  package.json
Labels: chore, size/XS

#2068 persisting filters
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
Labels: approved, size/S, fix

#2073 remarks glossary integration TM-2697
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/__snapshots__/RemarksGlossary.test.jsx.snap
Labels: approved, review required, size/XL

#2056 abl for post users - post client profile
  src/Components/AvailableBidder/AvailableBidderContainer/AvailableBidderContainer.jsx
  src/Components/AvailableBidder/AvailableBidderContainer/__snapshots__/AvailableBidderContainer.test.jsx.snap
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/Components/PostPage/PostPage.jsx
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Constants/Menu.js
  src/Containers/ProfilePublic/ProfilePublic.jsx
Labels: size/M, approved, review required, feature

#2075 Fix/agenda search
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/__snapshots__/RemarksGlossary.test.jsx.snap
  src/sass/_agendaItemMaintenance.scss
Labels: size/M, fix

#2072 Add Classifications to agenda item maintenance
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.test.jsx
  src/Components/Agenda/AgendaItemResearchPane/Classifications/Classifications.jsx
  src/Components/Agenda/AgendaItemResearchPane/Classifications/Classifications.test.jsx
  src/Components/Agenda/AgendaItemResearchPane/Classifications/index.js
  src/Components/Agenda/AgendaItemResearchPane/__snapshots__/AgendaItemResearchPane.test.jsx.snap
  src/Components/ProfileDashboard/Classifications/Classifications.jsx
  src/sass/_agendaItemMaintenance.scss
Labels: size/M, approved, review required, feature

#2080 adding dependency array to useEffect
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
Labels: size/XS, fix

#2015 aim legs edit
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/sass/_agenda.scss
  src/sass/_agendaItemMaintenance.scss
Labels: approved, review required, size/L

#2090 naming update
  src/Components/Agenda/AgendaItemResearchPane/AssignmentHistory/AssignmentHistory.jsx
Labels: approved, size/XS, fix

#2091 bypass prompt
  .circleci/config.yml
Labels: size/XS, fix

#2084 scroll tabs & removing ai research pane headers TM-2725
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/ProfileDashboard/Languages/Languages.jsx
  src/sass/_navTabs.scss
Labels: approved, size/S

#2088 abl sort presist TM-2802
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/Components/AvailableBidder/EditBidder/EditBidder.jsx
  src/Components/AvailableBidder/EditBidder/__snapshots__/EditBidder.test.jsx.snap
  src/actions/availableBidders.js
Labels: approved, size/S

#2092 fixing employee agendas url
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
Labels: size/XS, fix

#2096 Adding scroll to top button on agenda search page
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
Labels: approved, size/XS, fix

#2097 alphabetically order menus/sub menus
  src/Components/ProfileMenu/ProfileMenuExpanded/ProfileMenuExpanded.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
Labels: approved, size/L

#2094 external/internal abl export TM-2785
  src/Components/AvailableBidder/AvailableBidderContainer/AvailableBidderContainer.jsx
  src/Components/AvailableBidder/AvailableBidderContainer/__snapshots__/AvailableBidderContainer.test.jsx.snap
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/actions/availableBidders.js
  src/sass/_availableBidders.scss
Labels: size/M
