Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-06, with the labels that each got.

#2166 Changing Post Differential and Danger Pay to 0% instead of None
  src/Components/Differentials/Differentials.jsx
  src/Components/Differentials/__snapshots__/Differentials.test.jsx.snap
Labels: dual merge, size/XS, fix

#2156 reordering open positions sort dropdown
  src/Components/FavoritePositions/__snapshots__/FavoritePositions.test.jsx.snap
  src/Components/SelectForm/__snapshots__/SelectForm.test.jsx.snap
  src/Constants/Sort.js
Labels: size/L

#2087 integrate ai reference data
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/sass/_agendaItemMaintenance.scss
Labels: aging :older_adult:, approved, feature, size/XL

#2151 employee agenda client name url fix TM-2976
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/actions/agendaItemHistory.js
  src/reducers/agendaEmployees/index.js
Labels: dual merge, approved, size/S, fix

#2155 Adding "Updated" column to ABL
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/Constants/SystemMessages.js
  src/sass/_availableBidders.scss
  src/sass/_variables.scss
Labels: dual merge, approved, size/L, fix

#2187 remove cdo season filter flag TM-3030
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
Labels: approved, size/XS

#2188 remove bid stats flag TM-3030
  src/Constants/Menu.js
Labels: size/XS

#2189 remove client profiles flag TM-3030
  src/Constants/Menu.js
Labels: approved, size/S

#2181 remove client counts flag TM-3030
  src/Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx
  src/Containers/BidderPortfolio/BidderPortfolio.jsx
Labels: approved, size/S

#2190 remove tandem flag TM-3030
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
Labels: approved, size/XS

#2180 Collapsed Menu Sorting
  src/Components/ProfileMenu/ProfileMenuCollapsed/ProfileMenuCollapsed.jsx
  src/Components/ProfileMenu/ProfileMenuCollapsed/__snapshots__/ProfileMenuCollapsed.test.jsx.snap
Labels: approved, size/S, fix

#2186 Settings and Permissions
  src/Components/Settings/Settings.jsx
  src/Components/Settings/Settings.test.jsx
  src/Components/Settings/__snapshots__/Settings.test.jsx.snap
  src/sass/_profile.scss
Labels: approved, size/L, fix

#2182 update configs part2 TM-3030
  public/config/config.json
  public/config/config_dev.json
Labels: do not merge, approved, size/XS

#2196 remove bureau flag TM-3066
  src/Components/ProfileMenu/ProfileMenuCollapsed/__snapshots__/ProfileMenuCollapsed.test.jsx.snap
  src/Constants/Menu.js
Labels: size/XS

#2199 remove us codes flag TM-3066
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
Labels: size/XS

#2201 remove ao flag TM-3066
  src/Components/ProfileMenu/ProfileMenuCollapsed/__snapshots__/ProfileMenuCollapsed.test.jsx.snap
  src/Constants/Menu.js
Labels: size/XS

#2202 remove available bidders flag TM-3066
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Constants/Menu.js
Labels: size/M, approved

#2204 remove post flag TM-3066
  src/Components/ProfileMenu/ProfileMenuCollapsed/__snapshots__/ProfileMenuCollapsed.test.jsx.snap
  src/Constants/Menu.js
Labels: size/XS

#2203 remove classifications flag TM-3066
  src/Components/ProfileDashboard/Classifications/Classifications.jsx
Labels: approved, size/XS

#2205 remove step letters flag TM-3066
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/Components/AvailableBidder/EditBidder/EditBidder.jsx
Labels: approved, size/XS

#2197 update configs part3 TM-3066
  public/config/config.json
  public/config/config_dev.json
Labels: do not merge, approved, size/XS
