Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-03, with the labels that each got.

#1983 Integration with new data
  package.json
  public/config/config.json
  public/config/config_dev.json
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.test.jsx
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/Constants/Sort.js
  src/actions/agendaEmployees.js
  src/actions/agendaEmployees.test.js
  src/actions/agendaItemHistory.js
  src/reducers/agendaEmployees/agendaEmployees.js
  src/reducers/agendaEmployees/index.js
  src/sass/_agenda.scss
  src/sass/_variables.scss
  src/utilities.js
Labels: dual merge

#2018 Github actions
  .github/workflows/pr-labeler.yml
  .github/workflows/pr-review.yml
  .github/workflows/size-label.yml
Labels: approved, size/S, chore

#2022 update workflow
  .github/workflows/pr-labeler.yml
  .github/workflows/pr-review.yml
  .github/workflows/size-label.yml
Labels: chore, size/XS

#2014 isCreate no longer linked to aiHistory
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_agenda.scss
Labels: approved, size/S

#2043 Allow AOs to see the ABL
  src/Components/AvailableBidder/AvailableBidderContainer/AvailableBidderContainer.jsx
  src/Components/AvailableBidder/AvailableBidderContainer/__snapshots__/AvailableBidderContainer.test.jsx.snap
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/Components/BureauPage/BureauPage.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
Labels: size/M

#2044 Improved form validation for available bidder step letters and OC
  src/Components/AvailableBidder/EditBidder/EditBidder.jsx
  src/Components/AvailableBidder/EditBidder/__snapshots__/EditBidder.test.jsx.snap
  src/sass/_availableBidders.scss
Labels: approved, feature, size/L

#2034 asg hist integration
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/ProfileDashboard/Assignments/AssignmentsListResultsCard/AssignmentsContent/AssignmentsContent.jsx
  src/Constants/SystemMessages.js
Labels: dual merge, size/S

#2035 Remarks Glossary
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/__snapshots__/FrequentPositions.test.jsx.snap
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.test.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/__snapshots__/RemarksGlossary.test.jsx.snap
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/index.js
  src/Components/Glossary/GlossarySearch/__snapshots__/GlossarySearch.test.jsx.snap
  src/Components/SaveNewSearchDialog/__snapshots__/SaveNewSearchDialog.test.jsx.snap
  src/Components/TextInput/TextInput.jsx
  src/Components/TextInput/__snapshots__/TextInput.test.jsx.snap
  src/sass/_agendaItemMaintenance.scss
Labels: approved, review required, size/XXL, feature

#2048 Fix/research tab expand
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
Labels: approved, size/XS

#2052 sorting logs and showing more
  src/Components/AdministratorPage/Logs/Logs.jsx
Labels: approved, size/XS

#2053 updating grayed cols for ABL
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/sass/_availableBidders.scss
  src/sass/_variables.scss
Labels: size/S, fix

#2059 abl stats grade styling fix
  src/Components/AvailableBidder/AvailableBidderStats/AvailableBidderStats.jsx
  src/sass/_availableBidders.scss
Labels: size/S, fix

#2060 show abl stats for ao's
  src/Components/AvailableBidder/AvailableBidderContainer/AvailableBidderContainer.jsx
Labels: size/XS, fix
