Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-12, with the labels that each got.

#2402 Feature/add language data
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Constants/PropTypes.js
  src/actions/panelMeetingAgendas.js
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemLegsForm.scss
  src/sass/_panelMeetingAgendas.scss
Labels: approved, feature, size/L

#2409 TM-3691 remove sortby
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: approved, size/S, size/XS

#2411 TM-3700: UI Panel Meeting Link
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
Labels: enhancement, approved, size/S

#2412 TM-3699: Edit Agenda from Employee Agenda Search
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/sass/_employeeSearch.scss
Labels: enhancement, approved, size/S

#2413 TM-3701 update add edit button
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
Labels: approved, size/S

#2414 TM-3699 Adjustments
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/sass/_employeeSearch.scss
Labels: WIP, size/XS, fix

#2377 TM-3471: Client profile persist pagination
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
  src/Components/BidderPortfolio/BidControls/BidCyclePicker/BidCyclePicker.jsx
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/__snapshots__/BidderPortfolioPage.test.jsx.snap
  src/Components/BidderPortfolio/CDOAutoSuggest/CDOAutoSuggest.jsx
  src/Containers/BidderPortfolio/BidderPortfolio.jsx
  src/actions/bidderPortfolio.js
  src/reducers/bidderPortfolio/bidderPortfolio.js
  src/reducers/bidderPortfolio/index.js
Labels: approved, size/L

#2415 TM-3706 Edit Position Details
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/EditPositionDetails/EditPositionDetails.jsx
  src/Components/EditPositionDetails/PositionDetailsCard/PositionDetailsCard.jsx
  src/Components/EditPositionDetails/PositionDetailsCard/PositionDetailsCard.test.jsx
  src/Components/EditPositionDetails/PositionDetailsCard/__snapshots__/PositionDetailsCard.test.jsx.snap
  src/Components/EditPositionDetails/PositionDetailsCard/index.js
  src/actions/editPositionDetails.js
  src/actions/panelMeetingAgendas.js
Labels: WIP, approved, feature, size/XL

#2400 adding frequent positions to ai legs TM-3233
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/FrequentPositions.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/FrequentPositions.test.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/__snapshots__/FrequentPositions.test.jsx.snap
  src/Constants/SystemMessages.js
  src/actions/positions.js
  src/reducers/positions/index.js
  src/reducers/positions/positions.js
  src/reducers/positions/positions.test.js
  src/sass/_agendaItemMaintenance.scss
Labels: dual merge, approved, size/L

#2417 TM-3733 position search org-location-label
  src/Components/EditPositionDetails/PositionDetailsCard/PositionDetailsCard.jsx
  src/Components/ResultsCard/ResultsCard.jsx
  src/sass/_results.scss
Labels: approved, size/S
