Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-08, with the labels that each got.

#2255 TM-3236 - Agenda Item Save Button UI
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Constants/SystemMessages.js
  src/actions/agendaItemMaintenancePane.js
Labels: size/S

#2259 TM-3287 - Language and Position and Detail History for Private Profile
  public/config/config.json
  public/config/config_dev.json
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileContactInformation/UserProfileContactInformation.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileContactInformation/__snapshots__/UserProfileContactInformation.test.jsx.snap
  src/Containers/Dashboard/Dashboard.jsx
  src/Containers/ProfilePublic/ProfilePublic.jsx
  src/actions/userProfile.js
  src/sass/_profile.scss
Labels: size/L, fix

#2256 bid tracker hs register checkmark TM-3072
  src/Components/BidTracker/BidPhaseConfig/Complete.js
  src/Components/BidTracker/BidStep/BidStepIcon/BidStepIcon.jsx
  src/Components/BidTracker/BidStep/BidSteps.jsx
  src/sass/_bidTracker.scss
Labels: size/S, fix

#2252 Refactor ai legs TM-3248
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.test.jsx
  src/Components/Agenda/AgendaItemLegsForm/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/index.js
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.test.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/Agenda/AgendaLeg/index.js
  src/Components/NavTabs/NavTabs.jsx
  src/Components/NavTabs/__snapshots__/NavTabs.test.jsx.snap
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_navTabs.scss
  src/sass/styles.scss
Labels: approved, size/XXL

#2266 Bids and Assignments Ref Data
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
Labels: dual merge, approved, size/XS

#2258 Feature/update legs and other stuff
  public/config/config.json
  public/config/config_dev.json
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsForm/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.test.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/__snapshots__/AgendaItemMaintenanceContainer.test.jsx.snap
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.test.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/Agenda/Constants.js
  src/actions/agendaItemMaintenancePane.js
  src/sass/_agendaItemMaintenance.scss
Labels: approved, feature, size/XL

#2269 Feature/add asg bid leg
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/sass/_agendaItemMaintenance.scss
Labels: size/M, approved, feature

#2270 User Profiles - AO (Links and Classifications)
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/ProfileDashboard/Classifications/Classifications.jsx
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Containers/ProfilePublic/ProfilePublic.jsx
Labels: approved, size/S, fix

#2267 aih remarks pill text & color coding TM-3222 TM-3223
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
  src/Components/Agenda/RemarksPill/__snapshots__/RemarksPill.test.jsx.snap
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_variables.scss
Labels: dual merge, size/M, approved, fix

#2274 TM-3320: AO profile link on Employee Agenda page
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/Components/Agenda/EmployeeAgendaSearch/__snapshots__/EmployeeAgendaSearch.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  yarn.lock
Labels: approved, size/S, fix

#2273 panel meeting search row TM-3131
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.test.jsx
  src/Components/Panel/PanelMeetingSearchRow/__snapshots__/PanelMeetingSearchRow.test.jsx.snap
  src/Components/Panel/PanelMeetingSearchRow/index.js
  src/sass/_employeeSearch.scss
  src/sass/_panel.scss
Labels: approved, feature, size/XL

#2277 eas ao profile link
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
Labels: approved, size/XS, fix

#2279 fix eas ao profile link row view
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
Labels: approved, size/XS, fix

#2280 Wrapping up Create
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/actions/agendaItemMaintenancePane.js
Labels: dual merge, size/L

#2286 version update and cleanup
  package.json
  src/actions/agendaItemMaintenancePane.js
Labels: approved, size/XS

#2300 removing languages and asg for private profile
  src/Containers/Dashboard/Dashboard.jsx
Labels: approved, size/XS
