Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-09, with the labels that each got.

#2292 TM-3321 Hide Coming Soon on Position Details page
  src/Components/PositionDetailsItem/PositionDetailsContact/PositionDetailsContact.jsx
Labels: approved, size/S

#2293 TM-2709 Added Tool-tip to Featured Positions links
  src/Components/HomePagePositions/HomePagePositions.jsx
  src/Components/HomePagePositions/__snapshots__/HomePagePositions.test.jsx.snap
  src/Components/HomePagePositionsSection/HomePagePositionsSection.jsx
  src/Components/HomePagePositionsSection/__snapshots__/HomePagePositionsSection.test.jsx.snap
Labels: approved, size/S

#2306 post export
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/AvailableBidder/EditBidder/EditBidder.jsx
  src/actions/bureauPositions.js
  src/sass/_handshakeStatus.scss
Labels: size/S, fix

#2311 TM 3302 - TED Calendar Modal
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/sass/_agendaItemLegsForm.scss
Labels: size/M, approved, fix

#2307 aim legs row highlight on hover TM-3303 TM-3304
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/sass/_agendaItemLegsForm.scss
  src/sass/_variables.scss
Labels: approved, size/L

#2329 TM-3302 Fix: Removing padding from TED AIH modal
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/sass/_agendaItemLegsForm.scss
Labels: approved, size/XS, fix

#2330 aim leg dashes TM-3303
  src/sass/_agendaItemLegsForm.scss
Labels: approved, size/XS, fix

#2332 removing arrow row highlighting for aim legs TM-3304
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
Labels: approved, size/XS, fix

#2333 aim leg dashes pt2 TM-3303
  src/sass/_agendaItemLegsForm.scss
  src/sass/_variables.scss
Labels: approved, size/XS, fix

#2338 TM-3468: Available Bidders List - Freeze Top Row in Scroll
  src/sass/_availableBidders.scss
Labels: approved, size/XS, fix

#2336 aim styling refactor TM-3473
  src/sass/_agendaItemMaintenance.scss
Labels: approved, size/S, fix
