Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-05, with the labels that each got.

#2106 menu fallback
  src/Components/ProfileMenu/ProfileMenuExpanded/ProfileMenuExpanded.jsx
Labels: size/XS, fix

#2108 fix - snapshot
  src/Components/ProfileMenu/ProfileMenuExpanded/ProfileMenuExpanded.jsx
Labels: size/XS

#2103 slight rework
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
Labels: approved, size/XS

#2095 Adding shortcuts to remarks glossary in create agenda items page (TM-2717)
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/__snapshots__/RemarksGlossary.test.jsx.snap
  src/sass/_agendaItemMaintenance.scss
Labels: approved, size/S, fix

#2115 add-to-abl to row view
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/__snapshots__/BidderPortfolioStatRow.test.jsx.snap
  src/sass/_bidderPortfolio.scss
Labels: approved, size/XS, review required

#2124 Removed select all from Position Manager filters
  src/Components/BureauPage/PositionManager/PositionManager.jsx
Labels: size/XS, review required, fix

#2120 offer hs modal calendar styling
  src/sass/_handshakeModal.scss
Labels: approved, size/XS, review required, fix

#2104 aih employee name
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/actions/agendaItemHistory.js
  src/sass/_agenda.scss
  src/sass/_agendaItemMaintenance.scss
Labels: dual merge, size/M, approved

#2126 Update/remove bidding flag
  src/Components/PositionTitle/PositionTitle.jsx
  src/Components/PositionTitle/__snapshots__/PositionTitle.test.jsx.snap
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Components/ProfilePage/ProfilePage.jsx
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/ResultsCondensedCardBottom/ResultsCondensedCardBottom.jsx
  src/Components/ResultsCondensedCardBottom/__snapshots__/ResultsCondensedCardBottom.test.jsx.snap
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
  src/Constants/Menu.js
Labels: approved, size/L

#2130 Remove data_sync_admin flag
  src/Constants/Menu.js
Labels: size/S

#2128 Update/remove cdo bidding flag
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/ProfileDashboard/ProfileDashboard.jsx
Labels: approved, size/XS

#2129 Fixing resizing issue on different sized screens
  src/sass/_agendaItemMaintenance.scss
Labels: size/S, fix

#2136 remove confetti flag
  src/Components/BidTracker/BidStep/BidSteps.jsx
Labels: approved, size/XS

#2135 remove personalization flag
  src/Components/AccountDropdown/AccountDropdown.jsx
  src/Containers/DarkMode/DarkMode.jsx
Labels: approved, size/XS

#2134 Update/remove bid count flag
  src/Components/BidCount/FeatureFlagWrapper.jsx
  src/Components/BidCount/index.js
  src/Components/BidListResultsCard/BidContent/__snapshots__/BidContent.test.jsx.snap
  src/Components/BidTracker/BidTrackerCardTitle/__snapshots__/BidTrackerCardTitle.test.jsx.snap
  src/Components/CompareList/CompareList.jsx
  src/Components/CompareList/__snapshots__/CompareList.test.jsx.snap
  src/Components/PositionDetailsItem/PositionDetailsContact/__snapshots__/PositionDetailsContact.test.jsx.snap
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/ResultsCondensedCardBottom/ResultsCondensedCardBottom.jsx
  src/Components/ResultsCondensedCardBottom/__snapshots__/ResultsCondensedCardBottom.test.jsx.snap
  src/Components/ResultsCondensedCardStats/__snapshots__/ResultsCondensedCardStats.test.jsx.snap
Labels: approved, size/L

#2137 Update configs
  public/config/config.json
  public/config/config_dev.json
Labels: approved, size/XS

#2138 version number
  package.json
Labels: size/XS
