Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-11, with the labels that each got.

#2375 edit position details header & search bar TM-3574 TM-3575 TM-3576
  public/config/config.json
  public/config/config_dev.json
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/EditPositionDetails/EditPositionDetails.jsx
  src/Components/EditPositionDetails/EditPositionDetails.test.jsx
  src/Components/EditPositionDetails/__snapshots__/EditPositionDetails.test.jsx.snap
  src/Components/EditPositionDetails/index.js
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/Sort.js
  src/actions/editPositionDetails.js
  src/reducers/editPositionDetails/editPositionDetails.js
  src/reducers/editPositionDetails/index.js
  src/reducers/index.js
  src/sass/_editPositionDetails.scss
  src/sass/_panelSearch.scss
  src/sass/styles.scss
Labels: approved, size/XL

#2381 frequent positions EP integration
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/FrequentPositions.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/__snapshots__/FrequentPositions.test.jsx.snap
Labels: dual merge, approved, size/S, feature

#2378 TM-3560 Add authn false param to previous authn calls
  src/saml2-config.alt.js
  src/saml2-config.js
Labels: approved, size/XS, fix

#2384 Agenda Item Border Color Update TM-3345
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/Constants.js
Labels: approved, size/S

#2382 TM-3608: Update/panel agenda UI
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/actions/panelMeetingAgendas.js
  src/sass/_panelMeetingAgendas.scss
Labels: approved, size/L

#2391 update-filterby-TM3583
  src/sass/_bureau.scss
  src/sass/_employeeSearch.scss
  src/sass/_filterBy.scss
  src/sass/_panelMeetingAgendas.scss
  src/sass/_panelSearch.scss
  src/sass/styles.scss
Labels: size/M, approved

#2401 edit position details filterby
  src/sass/_editPositionDetails.scss
Labels: approved, size/S

#2392 panel meeting type label
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/sass/_panelMeetingAgendas.scss
Labels: size/M, approved, feature

#2397 update/bc-refactor
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_agendaItemHistory.scss
  src/sass/_borderColor.scss
  src/sass/_panelMeetingAgendas.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: size/M, approved

#2398 TM-3609: Add User Data to Panel Meeting Agendas
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/actions/panelMeetingAgendas.js
  src/sass/_panelMeetingAgendas.scss
Labels: approved, size/S

#2396 panel meeting agenda filter spacing TM-3619
  src/sass/_panelMeetingAgendas.scss
Labels: approved, size/XS, fix
