Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-07, with the labels that each got.

#2215 update abl error message handling TM-3069
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
Labels: approved, size/S

#2216 Adding Remarks addition/subtraction functionality
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.test.jsx
  src/Components/Agenda/RemarksPill/__snapshots__/RemarksPill.test.jsx.snap
Labels: approved, size/L

#2214 make Location consistent for PV favorite
  src/Components/ResultsCondensedCardTop/ResultsCondensedCardTop.jsx
  src/utilities.js
Labels: approved, size/XS

#2225 Separating ML and ID panel dates
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: approved, size/S, fix

#2224 panel meeting search route TM-3129
  public/config/config.json
  public/config/config_dev.json
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.test.jsx
  src/Components/Panel/PanelMeetingSearch/__snapshots__/PanelMeetingSearch.test.jsx.snap
  src/Components/Panel/PanelMeetingSearch/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/sass/_panel.scss
  src/sass/styles.scss
Labels: approved, feature, size/L

#2217 TOD, Travel, and Action AI Legs integration and updates
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/sass/_agenda.scss
  src/sass/_agendaItemMaintenance.scss
Labels: dual merge, approved, size/L

#2239 Fix sort
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
Labels: approved, size/XS, fix

#2234 Code Coverage - Agenda Item Maintenance
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.test.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/__snapshots__/AgendaItemMaintenanceContainer.test.jsx.snap
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.test.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.test.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.test.jsx
  src/Components/Agenda/RemarksPill/__snapshots__/RemarksPill.test.jsx.snap
Labels: approved, size/L, fix

#2235 Panel Meeting - Search Results Controls
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearch/__snapshots__/PanelMeetingSearch.test.jsx.snap
  src/Constants/Sort.js
  src/actions/availableBidders.js
  src/sass/_panel.scss
Labels: approved, size/L, fix

#2232 Look up position and add as leg if valid
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.test.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.test.jsx
  src/actions/agendaItemMaintenancePane.js
  src/hooks.js
  src/reducers/agendaItemMaintenancePane/agendaItemMaintenancePane.js
  src/reducers/agendaItemMaintenancePane/index.js
  src/reducers/index.js
  src/sass/_agendaItemMaintenance.scss
Labels: size/XL

#2240 Remove Leg
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.test.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
Labels: approved, size/L

#2246 transitioning AIM position add to generic url TM-3258
  .github/pull_request_template.md
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/actions/positions.js
  src/reducers/index.js
  src/reducers/positions/index.js
  src/reducers/positions/positions.js
  src/reducers/positions/positions.test.js
Labels: dual merge, size/M, approved

#2248 clean-up of styling and code organization TM-3184
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_employeeSearch.scss
  src/sass/_navTabs.scss
  src/sass/_profile.scss
  src/sass/styles.scss
Labels: approved, size/XXL
