Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2022-10, with the labels that each got.

#2344 Added placeholder text to the fields
  src/Components/AvailableBidder/EditBidder/EditBidder.jsx
  src/Components/AvailableBidder/EditBidder/__snapshots__/EditBidder.test.jsx.snap
Labels: size/XS

#2345 adding updated column to external abl view TM-3477
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/sass/_variables.scss
Labels: dual merge, approved, size/XS

#2347 TM-3457 - AIM Button Alignment
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/sass/_agendaItemMaintenance.scss
Labels: approved, size/XS, fix

#2343 Updated display logic for handshake icon
  src/Components/BureauPage/PositionManagerBidders/PositionManagerBidders.jsx
Labels: approved, size/XS

#2346 abl export button float fix TM-3198
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/sass/_availableBidders.scss
Labels: approved, size/XS, fix

#2348 TM-3451 - AIM Menu Alignment
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/sass/_agendaItemMaintenance.scss
Labels: approved, size/S, fix

#2350 fix eas card styling - buttons shifting TM-3355
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/sass/_employeeSearch.scss
Labels: size/L, fix, Approved Pending Feedback

#2339 Fixed Sort - Positions Manager > Candidates list
  src/Components/BureauPage/PositionManagerDetails/PositionManagerDetails.jsx
  src/Constants/Sort.js
Labels: size/XS

#2349 Fixed to fetch all 4 fav-services
  src/Containers/Favorites/Favorites.jsx
Labels: approved, size/S

#2361 remove updated from external abl
  src/Components/AvailableBidder/AvailableBidderRow/AvailableBidderRow.jsx
  src/Components/AvailableBidder/AvailableBidderTable/AvailableBidderTable.jsx
  src/sass/_variables.scss
Labels: size/XS, fix

#2364 Removed unused code
  src/Containers/BidderPortfolio/BidderPortfolio.jsx
  src/actions/bidderPortfolio.js
  src/actions/bidderPortfolio.test.js
Labels: size/M, approved

#2334 updating ignore versions
  .github/dependabot.yml
Labels: approved, size/XS

#2367 TM-3532: Change "Capsule" to "Position Details"
  src/Components/PositionDetailsItem/PositionDetailsContact/PositionDetailsContact.jsx
  src/Components/PositionDetailsItem/PositionDetailsContact/__snapshots__/PositionDetailsContact.test.jsx.snap
Labels: approved, size/XS, fix

#2369 yaml syntax file update
  .github/dependabot.yml
Labels: size/XS, fix

#2368 bureau has hs reg process TM-3508
  src/Components/BureauPage/PositionManagerBidders/PositionManagerBidders.jsx
  src/Components/Handshake/HandshakeBureauButton/HandshakeBureauButton.jsx
Labels: approved, size/XS

#2374 TM-3554: Update/panel meeting agenda routes
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Components/Panel/PanelMeetingAgenda/PanelMeetingAgenda.jsx
  src/Components/Panel/PanelMeetingAgenda/PanelMeetingAgenda.test.jsx
  src/Components/Panel/PanelMeetingAgenda/__snapshots__/PanelMeetingAgenda.test.jsx.snap
  src/Components/Panel/PanelMeetingAgenda/index.js
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Components/Panel/PanelMeetingSearchRow/__snapshots__/PanelMeetingSearchRow.test.jsx.snap
  src/sass/_panel.scss
Labels: approved, size/L

#2365 insertion text for remarks
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.test.jsx
  src/Components/Agenda/RemarksPill/__snapshots__/RemarksPill.test.jsx.snap
  src/sass/_agendaItemMaintenance.scss
Labels: dual merge, approved, feature, size/L

#2376 removing data points border from panel meeting agendas header
  src/sass/_panelMeetingAgendas.scss
Labels: approved, size/XS, fix
