Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-08, with the labels that each got.

#2649 [TM-4684] Feature Flags Update
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/FeatureFlags/FeatureFlags.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Constants/Menu.js
  src/sass/_administrator.scss
Labels: Approved :heavy_check_mark:, size/L

#2646 TM-4649 & TM-4562: Add Override TOD and Functional Bureau to Publishable Position card
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.test.jsx
  src/sass/_positionContent.scss
Labels: size/M, Approved :heavy_check_mark:, feature

#2656 Updates to Employee Profile
  src/Components/ProfileDashboard/Classifications/Classifications.jsx
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfile.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
  src/Containers/Dashboard/Dashboard.jsx
  src/Containers/ProfilePublic/ProfilePublic.jsx
Labels: dual merge, Release, size/M

#2660 useLayoutEffect
  src/Components/HrOnlineIFrame/HrOnlineIFrame.jsx
Labels: Release, Approved :heavy_check_mark:, size/XS

#2659 Clean up create and disable edit
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/actions/editRemark.js
Labels: dual merge, Release, Approved :heavy_check_mark:, size/S

#2662 TM Version 11.0
  package.json
Labels: dual merge, Release, size/XS

#2667 TM-4708-Manage-Post-Access
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
  src/Components/ManagePostAccess/ManagePostAccess.jsx
  src/Components/ManagePostAccess/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/actions/managePostAccess.js
  src/actions/searchPostAccess.js
  src/reducers/index.js
  src/reducers/managePostAccess/index.js
  src/reducers/managePostAccess/managePostAccess.js
  src/reducers/searchPostAccess/index.js
Labels: Approved :heavy_check_mark:, size/XL

#2645 [TM-4668/4737] Run Panel Post Panel
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.test.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
  src/Components/NavTabs/NavTabs.jsx
  src/Components/Panel/helpers.js
  src/Constants/SystemMessages.js
  src/actions/postPanelProcessing.js
  src/reducers/index.js
  src/reducers/postPanelProcessing/index.js
  src/reducers/postPanelProcessing/postPanelProcessing.js
  src/sass/_common.scss
  src/sass/_datePicker.scss
  src/sass/_navTabs.scss
  src/sass/_panelAdmin.scss
  src/sass/_positionContent.scss
Labels: Approved :heavy_check_mark:, size/XXL, feature

#2664 [TM-4706] Position Classifications
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/NavTabs/NavTabs.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/Components/TabbedCard/TabbedCard.jsx
  src/actions/publishablePositions.js
  src/sass/_navTabs.scss
  src/sass/_positionContent.scss
Labels: Approved :heavy_check_mark:, feature, size/XL

#2651 TM-4521: Pay Plan field - Panel Agenda items
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/sass/_agendaItemLegsForm.scss
Labels: Approved :heavy_check_mark:, size/S, feature

#2668 styling touch ups for post access page
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
  src/Components/ManagePostAccess/ManagePostAccess.jsx
  src/sass/_postAccess.scss
  src/sass/_variables.scss
Labels: Approved :heavy_check_mark:, size/S

#2652 TM-4651-Manage-Bid-Seasons
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/ManageBidSeasons/EditBidSeasons.jsx
  src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasons.jsx
  src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasonsCard.jsx
  src/Components/AdministratorPage/ManageBidSeasons/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/actions/BidSeasons.js
  src/reducers/bidSeasons/bidSeasons.js
  src/reducers/bidSeasons/index.js
  src/reducers/index.js
  src/sass/_bidSeasons.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: size/XXL

#2669 TM-4708-Post-Access-Filters-Checkbox
  src/Components/ManagePostAccess/ManagePostAccess.jsx
  src/sass/_postAccess.scss
Labels: size/M, Approved :heavy_check_mark:, feature

#2677 [TM-4737] Run Panel Post Panel Autofill Inputs on Run
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
Labels: Approved :heavy_check_mark:, size/S
