Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-03, with the labels that each got.

#2477 TM-4034, update CDO & AO agenda and meeting icons
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
Labels: good first issue, approved, size/S, review required

#2478 Update/agenda cards header
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_agendaItemHistory.scss
  src/sass/_panelMeetingAgendas.scss
Labels: dual merge, size/M, approved

#2480 Panel Meetings Search - reset page on filters change
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
Labels: approved, size/XS, fix

#2484 PMA - Filters TM-4138
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: size/M, approved, fix, Approved Pending Feedback

#2483 Update/pm filter sort default TM-4131
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Constants/Sort.js
  src/sass/_bureau.scss
  src/sass/_filters.scss
  src/sass/_inputs.scss
  src/sass/_panelSearch.scss
  src/sass/styles.scss
Labels: size/M, approved

#2487 Scroll AI Legs TM-4133
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_agendaItemRow.scss
  src/sass/_panelMeetingAgendas.scss
  src/sass/_remarks.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: approved, size/XL

#2486 link eas pmd to pm TM-4033
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
Labels: dual merge, approved, size/S

#2476 verify all leg data is coming through TM-4029
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/FrequentPositions.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/__snapshots__/FrequentPositions.test.jsx.snap
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_panelMeetingAgendas.scss
Labels: size/XL

#2489 eas filters clean up TM-4036
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/Components/BureauPage/PositionManager/PositionManagerSearch/PositionManagerSearch.jsx
  src/Components/ResultsMultiSearchHeader/__snapshots__/ResultsMultiSearchHeader.test.jsx.snap
  src/Components/ResultsSearchHeader/__snapshots__/ResultsSearchHeader.test.jsx.snap
  src/Components/SearchBar/SearchBar.jsx
  src/Components/SearchBar/__snapshots__/SearchBar.test.jsx.snap
  src/sass/_employeeSearch.scss
Labels: size/M, approved

#2492 fix for aih cards
  src/sass/_agendaItemRow.scss
Labels: approved, size/XS, fix

#2493 temporarily comment out remarks rendering for glossary
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
Labels: size/S, fix

#2485 TM-4134, add timestamp to created and modified by agenda item
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_panelMeetingAgendas.scss
Labels: approved, size/S

#2488 TM-3905: changing FE to read new API location fields
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/sass/_employeeSearch.scss
Labels: approved, size/S, Approved Pending Feedback

#2496 Fix/creator modifier name
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_panelMeetingAgendas.scss
Labels: approved, size/XS, fix

#2497 Implement cool chaining operator and cleanup mapping
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
Labels: approved, size/XS

#2500 adding icon to pmiNum and removing Edit Pencil
  .eslintrc
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemRow.scss
  src/sass/_panelMeetingAgendas.scss
Labels: size/M, approved, feature

#2495 TM-4129 remarks read on new structure
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_panelMeetingAgendas.scss
Labels: dual merge, approved, feature, size/L

#2494 TM-4040, Ai Maintenance, employee name placeholder
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
Labels: approved, size/S

#2504 updating url for dev1
  src/server-alt.js
Labels: approved, size/XS

#2505 Update mapping for tod desc
  src/Components/ProfileDashboard/Assignments/AssignmentsListResultsCard/AssignmentsContent/AssignmentsContent.jsx
Labels: approved, size/XS, fix

#2498 ff review release 10.0 TM-4135 TM-4195
  public/config/config.json
  public/config/config_dev.json
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Components/ProfileDashboard/AgendaItemHistoryLink/AgendaItemHistoryLink.jsx
  src/Constants/Menu.js
Labels: do not merge, approved, feature, size/L

#2514 Updating version - 10.0
  package.json
Labels: dual merge, Release, approved, size/XS

#2501 TM-4110, AIM only show active remarks in glossary
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
Labels: approved, size/XS

#2502 TM-4039, add created and updated by timestamps to AIM
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/Constants.js
  src/sass/_agendaItemMaintenance.scss
  src/sass/_panelMeetingAgendas.scss
Labels: size/M, approved

#2520 updates for new data fields
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
Labels: dual merge, Release, approved, size/S

#2524 Update name to code for unique key for li
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: approved, size/XS, fix

#2527 TM-4016: aim individual error states - new
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/sass/_agendaItemMaintenance.scss
Labels: approved, size/L, Approved Pending Feedback

#2508 TM-4042 & TM-4043: Moving around AIM dropdowns and adding FP tab link
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/sass/_agendaItemMaintenance.scss
Labels: approved, size/L, fix
