Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-11, with the labels that each got.

#2751 TM-4991-Panel-Languages
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/utilities.js
Labels: size/XS

#2753 Fix Circle Ci Issue
  package.json
  yarn.lock
Labels: dependencies, size/XS, fix

#2755 increase permissions for labeler
  .github/workflows/size-label.yml
Labels: size/XS

#2758 TM-5000 alert for bid seasons
  src/Components/AdministratorPage/ManageBidSeasons/EditBidSeasons.jsx
  src/Components/Alert/Alert.tsx
  src/sass/_overrides.scss
Labels: dual merge, size/S

#2754 [TM-5052] Run Panel Hold
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
  src/sass/_positionContent.scss
Labels: size/L

#2752 [TM-5024] Run Panel Follow-Up (Miscellaneous)
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
  src/sass/_positionContent.scss
Labels: size/L

#2757 TM-5010: standardizing capitalization across cards
  src/Components/BidListResultsCard/BidContent/BidContent.jsx
  src/Components/BidListResultsCard/BidContent/__snapshots__/BidContent.test.jsx.snap
  src/Components/BureauPage/BureauResultsCard/BureauResultsCard.jsx
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/BureauPage/ProjectedVacancy/index.js
  src/Components/CompareList/CompareList.jsx
  src/Components/CompareList/__snapshots__/CompareList.test.jsx.snap
  src/Components/PositionDetailsItem/PositionDetailsItem.jsx
  src/Components/PositionDetailsItem/__snapshots__/PositionDetailsItem.test.jsx.snap
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/ResultsCondensedCardFooter/ResultsCondensedCardFooter.jsx
  src/Components/ResultsCondensedCardFooter/__snapshots__/ResultsCondensedCardFooter.test.jsx.snap
  src/Components/ResultsCondensedCardTop/ResultsCondensedCardTop.jsx
  src/Components/Ribbon/ServiceNeedDifferential/ServiceNeedDifferential.jsx
  src/Components/Ribbon/ServiceNeedDifferential/ServiceNeedDifferential.test.jsx
  src/Components/Ribbon/ServiceNeedDifferential/__snapshots__/ServiceNeedDifferential.test.jsx.snap
Labels: size/M

#2744 TM-4910-Bureau-Exception-List-API-Integration
  src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
  src/Components/AdministratorPage/BureauExceptionList/BureauExceptionListCard.jsx
  src/Constants/SystemMessages.js
  src/actions/bureauException.js
  src/reducers/bureauException/bureauException.js
  src/reducers/bureauException/index.js
  src/sass/_bureauExceptionList.scss
Labels: WIP, size/XL

#2680 [TM-4845] Position Classifications Integration
  src/Components/PublishablePositionCard/PositionClassification/PositionClassification.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Constants/SystemMessages.js
  src/actions/positionClassifications.js
  src/reducers/index.js
  src/reducers/positionClassifications/index.js
  src/reducers/positionClassifications/positionClassifications.js
  src/reducers/positionClassifications/positionClassifications.test.js
Labels: feature, size/XL

#2760 Bureau-Exception-List Header
  src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
  src/Components/AdministratorPage/BureauExceptionList/BureauExceptionListCard.jsx
  src/sass/_bureauExceptionList.scss
Labels: size/S

#2762 TM-5070 Pt1 - Renaming Bureau Exceptions functions and file names
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/BureauExceptionList/index.js
  src/Components/AdministratorPage/BureauExceptions/BureauExceptions.jsx
  src/Components/AdministratorPage/BureauExceptions/BureauExceptionsCard.jsx
  src/Components/AdministratorPage/BureauExceptions/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/actions/bureauException.js
  src/actions/bureauExceptions.js
  src/reducers/bureauException/bureauException.js
  src/reducers/bureauException/index.js
  src/reducers/bureauExceptions/bureauExceptions.js
  src/reducers/bureauExceptions/index.js
  src/reducers/index.js
  src/sass/_bureauExceptions.scss
  src/sass/styles.scss
Labels: dual merge, size/XL

#2740 Release 11.2
  package.json
  public/config/config.json
  public/config/config_dev.json
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/Constants/Menu.js
  src/Constants/Sort.js
  src/actions/publishablePositions.js
  src/actions/userProfilePublic.js
  src/sass/_employeeSearch.scss
  src/sass/_searchBar.scss
  src/sass/_variables.scss
Labels: dual merge, size/XL

#2764 [TM-5059] Panel Meeting Agenda Remarks - Hold
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
Labels: size/XS

#2763 TM-4987: Assignment History Date Bug
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/utilities.js
Labels: size/XS, Approved Pending Feedback :stopwatch:

#2770 TM-4446, remove completed status from panel meetings
  src/Components/Panel/PanelMeetingTracker/__snapshots__/PanelMeetingTracker.test.jsx.snap
  src/Components/Panel/helpers.js
Labels: Approved :heavy_check_mark:, size/XS

#2769 TM-4999-Panel-Agenda-Items-Languages
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
Labels: WIP, Approved :heavy_check_mark:, size/S

#2765 TM-4988 custom date picker
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/TMDatePicker/TMDatePicker.jsx
  src/Components/TMDatePicker/index.js
  src/sass/_datePicker.scss
Labels: size/M, Approved :heavy_check_mark:

#2772 TM-4999-Agenda-UI
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2771 bugfix, touch up assignments list
  src/Components/ProfileDashboard/Assignments/AssignmentsList.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2766 TM-5070 Pt2 - BEL Refactor
  src/Components/AdministratorPage/BureauExceptions/BureauExceptions.jsx
  src/Components/AdministratorPage/BureauExceptions/BureauExceptionsCard.jsx
  src/actions/bureauExceptions.js
  src/reducers/bureauExceptions/bureauExceptions.js
  src/reducers/bureauExceptions/index.js
  src/sass/_bureauExceptions.scss
  src/sass/_common.scss
  src/utilities.js
Labels: dual merge, Approved :heavy_check_mark:, size/XL
