Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-07, with the labels that each got.

#2600 TM-3813, Cycle Management - New Page & Search
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
  src/reducers/index.js
  src/sass/_bureau.scss
Labels: Approved :heavy_check_mark:, size/XL

#2595 Additional download set up for redacted
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/__snapshots__/UserProfileGeneralInformation.test.jsx.snap
  src/Constants/PropTypes.js
  src/Containers/ProfilePublic/ProfilePublic.jsx
  src/actions/userProfilePublic.js
Labels: dual merge, size/M, Approved :heavy_check_mark:

#2597 Tm 4584 UI projected vacancies page and search
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/ProjectedVacancy/index.js
  src/Components/BureauPage/ProjectedVacancy/projectedVacancy.jsx
  src/Components/ProfileMenu/NavLink/NavLink.jsx
  src/Components/ProfileMenu/NavLink/__snapshots__/NavLink.test.jsx.snap
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/actions/projectedVacancy.js
  src/reducers/index.js
  src/reducers/projectedVacancy/index.js
  src/reducers/projectedVacancy/projectedVacancy.js
  src/sass/_profile.scss
  src/sass/_projectedVacancy.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, size/XXL

#2598 [TM-3816] Publishable Position Card
  src/Components/DefinitionList/Definition/Definition.jsx
  src/Components/EditPositionDetails/EditPositionDetails.jsx
  src/Components/NavTabs/NavTabs.jsx
  src/Components/NavTabs/__snapshots__/NavTabs.test.jsx.snap
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.test.jsx
  src/Components/PositionExpandableContent/index.js
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.test.jsx
  src/Components/PublishablePositionCard/index.js
  src/Components/TabbedCard/TabbedCard.jsx
  src/Components/TabbedCard/TabbedCard.test.jsx
  src/Components/TabbedCard/index.js
  src/sass/_navTabs.scss
  src/sass/_positionContent.scss
  src/sass/_tabbedCard.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, feature, size/XL

#2602 [TM-4581] Publishable Positions Page
  src/Components/EditPositionDetails/EditPositionDetails.jsx
  src/sass/_bureau.scss
  src/sass/_editPositionDetails.scss
Labels: feature, size/XL

#2594 techdebt cleanup
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/Dashboard/Dashboard.jsx
  src/Components/PostPage/PostPage.jsx
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfile.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
  src/Components/ProfileDashboard/UserProfile/__snapshots__/UserProfile.test.jsx.snap
  src/Components/ProfileMenu/ProfileMenuCollapsed/__snapshots__/ProfileMenuCollapsed.test.jsx.snap
  src/Constants/Menu.js
Labels: Approved :heavy_check_mark:, size/S

#2603 TM-4595: Consolidating two ted fields
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/sass/_agendaItemLegsForm.scss
Labels: Approved :heavy_check_mark:, size/S, fix

#2604 remove mutually exclusive logic
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.test.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.test.jsx
  src/Constants/PropTypes.js
  src/sass/_panelAdmin.scss
Labels: size/M, Approved :heavy_check_mark:

#2609 TechDebt: moving formatLang to common file
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/utilities.js
  src/utilities.tsx
Labels: Approved :heavy_check_mark:, size/S

#2613 [TM-3820] Common Editable and Expandable Position Card Content
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/sass/_positionContent.scss
Labels: Approved :heavy_check_mark:, size/L

#2606 TM-3819, cycle search results
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/actions/cycleManagement.js
  src/sass/_positionSearch.scss
Labels: Approved :heavy_check_mark:, size/L

#2605 changed the hard sidebar width to change with sidebar is minimized
  src/Components/ProfileMenu/NavLink/NavLink.jsx
  src/Components/ProfileMenu/NavLink/__snapshots__/NavLink.test.jsx.snap
  src/sass/_profile.scss
Labels: Approved :heavy_check_mark:, size/S

#2617 menu fixes
  src/sass/_profile.scss
Labels: Approved :heavy_check_mark:, size/XS, fix

#2618 TM-3819, add admin placeholder functionality in Cycle Search
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/sass/_positionSearch.scss
Labels: Approved :heavy_check_mark:, size/S

#2601 Feature/sep
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/GsaLocations/GsaLocations.jsx
  src/Components/Agenda/AgendaItemResearchPane/GsaLocations/index.js
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/TotalResults/TotalResults.jsx
  src/actions/gsaLocations.js
  src/reducers/gsaLocations/gsaLocations.js
  src/reducers/gsaLocations/index.js
  src/reducers/index.js
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_pagination.scss
  src/sass/_spinner.scss
  src/sass/_variables.scss
  src/utilities.js
Labels: dual merge, Approved :heavy_check_mark:, size/XL

#2614 TM-4585: Projected Vacancies Card
  src/Components/BureauPage/ProjectedVacancy/projectedVacancy.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.test.jsx
  src/Components/ProjectedVacancyCard/index.js
  src/Components/ResultsCard/ResultsCard.jsx
  src/sass/_positionContent.scss
Labels: Approved :heavy_check_mark:, feature, size/L

#2615 TM-3735: Cycle Position Search Page
  public/config/config.json
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.test.jsx
  src/Components/CycleManagement/CyclePositionSearch/__snapshots__/CyclePositionSearch.test.jsx.snap
  src/Components/CycleManagement/CyclePositionSearch/index.js
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
  src/sass/_common.scss
  src/sass/_positionSearch.scss
Labels: Approved :heavy_check_mark:, feature, size/XL

#2623 Cycle Search Page Cleanup
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/actions/cycleManagement.js
  src/sass/_positionSearch.scss
Labels: size/M, Approved :heavy_check_mark:

#2624 add edit button for testing
  src/Components/CyclePositionCard/CyclePositionCard.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2616 [TM-3820] Edit Publishable Position Card
  src/Components/EditPositionDetails/EditPositionDetails.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProfileMenu/ProfileMenuCollapsed/ProfileMenuCollapsed.jsx
  src/Components/ProfileMenu/ProfileMenuCollapsed/__snapshots__/ProfileMenuCollapsed.test.jsx.snap
  src/Components/ProfileMenu/ProfileMenuExpanded/ProfileMenuExpanded.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Constants/SystemMessages.js
  src/actions/editPositionDetails.js
  src/reducers/editPositionDetails/editPositionDetails.js
  src/reducers/editPositionDetails/index.js
  src/sass/_common.scss
  src/sass/_positionContent.scss
  src/sass/_profile.scss
Labels: Approved :heavy_check_mark:, feature, size/L

#2625 Fix - Adding status to cps subheader
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/sass/_positionSearch.scss
Labels: Approved :heavy_check_mark:, size/XS, fix

#2635 AO Page
  src/Components/AoPage/AoPage.jsx
  src/Components/AoPage/AoPage.test.jsx
  src/Components/AoPage/AoPageLoadable.jsx
  src/Components/AoPage/index.js
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Components/ProfilePage/ProfilePage.jsx
  src/Containers/Ao/Ao.jsx
  src/Containers/Ao/Ao.test.jsx
  src/Containers/Ao/index.js
Labels: size/M, Approved :heavy_check_mark:

#2628 TM-4583, cycle position search edit
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/CyclePositionCard/CyclePositionCard.test.jsx
  src/Constants/SystemMessages.js
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
  src/sass/_positionContent.scss
  src/sass/_positionSearch.scss
Labels: Approved :heavy_check_mark:, size/L

#2626 TM-4586 projected vacancy edit
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/ProjectedVacancy/projectedVacancy.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.test.jsx
  src/Components/TabbedCard/TabbedCard.jsx
  src/Constants/SystemMessages.js
  src/actions/projectedVacancy.js
  src/actions/publishablePositions.js
  src/reducers/projectedVacancy/index.js
  src/reducers/projectedVacancy/projectedVacancy.js
  src/sass/_common.scss
  src/sass/_datePicker.scss
  src/sass/_pagination.scss
  src/sass/_positionContent.scss
  src/sass/_positionSearch.scss
  src/sass/_tabbedCard.scss
Labels: Approved :heavy_check_mark:, feature, size/XL

#2638 better dummy data names
  src/Components/CyclePositionCard/CyclePositionCard.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2631 TM-4650 (Section Three) consolidating filter styles
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/BureauPage/ProjectedVacancy/projectedVacancy.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/sass/_common.scss
  src/sass/_employeeSearch.scss
  src/sass/_panelMeetingAgendas.scss
  src/sass/_panelSearch.scss
  src/sass/_positionSearch.scss
  src/sass/_variables.scss
Labels: Approved :heavy_check_mark:, size/L

#2637 TM-4650 (Section One) WS Updates to new pages
  public/config/config.json
  public/config/config_dev.json
  src/Components/BureauPage/ProjectedVacancy/projectedVacancy.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/Constants/Menu.js
  src/sass/_common.scss
Labels: Approved :heavy_check_mark:, size/XL

#2640 TM-3088, Employee Profile Updates
  src/Components/ProfileDashboard/Assignments/AssignmentsList.jsx
  src/Components/ProfileDashboard/Assignments/AssignmentsListResultsCard/AssignmentsContent/AssignmentsContent.jsx
  src/Components/ProfileDashboard/Assignments/AssignmentsListResultsCard/AssignmentsContent/__snapshots__/AssignmentsContent.test.jsx.snap
  src/Components/ProfileDashboard/ExternalUserStatus/ExternalUserStatus.jsx
  src/Components/ProfileDashboard/ExternalUserStatus/__snapshots__/ExternalUserStatus.test.jsx.snap
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfile.jsx
  src/Components/ProfileDashboard/UserProfile/__snapshots__/UserProfile.test.jsx.snap
  src/Containers/Dashboard/Dashboard.jsx
  src/Containers/ProfilePublic/ProfilePublic.jsx
  src/sass/_common.scss
  src/sass/_profile.scss
Labels: size/M, Approved :heavy_check_mark:

#2641 Emp profile link update
  src/Components/About/Content/__snapshots__/Content.test.jsx.snap
  src/Components/Alert/Alert.tsx
  src/Components/BidderPortfolio/BidderPortfolioContainer/__snapshots__/BidderPortfolioContainer.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorCardList/__snapshots__/GlossaryEditorCardList.test.jsx.snap
  src/Components/GlossaryEditor/GlossaryEditorPageHeader/__snapshots__/GlossaryEditorPageHeader.test.jsx.snap
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileModal.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/__snapshots__/UserProfileGeneralInformation.test.jsx.snap
  src/Components/SaveNewSearchAlert/__snapshots__/SaveNewSearchAlert.test.jsx.snap
  src/Containers/ProfilePublic/ProfilePublic.jsx
  src/sass/_common.scss
  src/sass/_overrides.scss
  src/sass/_profile.scss
Labels: size/XL

#2639 TM-4650 (Section Four) disable filters and paginate on Edit mode
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/BureauPage/ProjectedVacancy/projectedVacancy.jsx
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/FavoritePositions/__snapshots__/FavoritePositions.test.jsx.snap
  src/Components/Notifications/__snapshots__/Notifications.test.jsx.snap
  src/Components/PaginationWrapper/PaginationWrapper.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/Components/ResultsContainer/__snapshots__/ResultsContainer.test.jsx.snap
  src/sass/_common.scss
  src/sass/_overrides.scss
  src/utilities.js
Labels: Approved :heavy_check_mark:, size/XL
