Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-09, with the labels that each got.

#2673 TM-4847, Search Post Access API
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
  src/actions/searchPostAccess.js
  src/reducers/searchPostAccess/index.js
  src/reducers/searchPostAccess/searchPostAccess.js
  src/sass/_postAccess.scss
Labels: Approved :heavy_check_mark:, size/XL

#2657 Add assignment maintenance page
  src/Components/AdministratorPage/UserRoles/UserRow/__snapshots__/UserRow.test.jsx.snap
  src/Components/AoPage/AoPage.jsx
  src/Components/Assignments/AssignmentCard/AssignmentCard.jsx
  src/Components/Assignments/AssignmentCard/AssignmentCard.test.jsx
  src/Components/Assignments/AssignmentCard/index.js
  src/Components/Assignments/Assignments.jsx
  src/Components/Assignments/Assignments.test.jsx
  src/Components/Assignments/__snapshots__/Assignments.test.jsx.snap
  src/Components/Assignments/index.js
  src/Components/BidderPortfolio/BidControls/BidCyclePicker/ListItem/__snapshots__/ListItem.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioCardList/BidderPortfolioCardList.jsx
  src/Components/BidderPortfolio/BidderPortfolioCardList/__snapshots__/BidderPortfolioCardList.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
  src/Components/BidderPortfolio/BidderPortfolioGridItem/__snapshots__/BidderPortfolioGridItem.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioGridList/BidderPortfolioGridList.jsx
  src/Components/BidderPortfolio/BidderPortfolioGridList/__snapshots__/BidderPortfolioGridList.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioGridListHeader/__snapshots__/BidderPortfolioGridListHeader.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/__snapshots__/BidderPortfolioPage.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Components/CheckBox/CheckBox.jsx
  src/Components/FeedbackForm/__snapshots__/FeedbackForm.test.jsx.snap
  src/Components/Notifications/NotificationRow/__snapshots__/NotificationRow.test.jsx.snap
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProfileDashboard/Assignments/AssignmentsList.jsx
  src/Components/ProfileDashboard/Assignments/__snapshots__/AssignmentsList.test.jsx.snap
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/SearchFilters/BooleanFilter/__snapshots__/BooleanFilter.test.jsx.snap
  src/Components/SearchFilters/BureauFilter/__snapshots__/BureauFilter.test.jsx.snap
  src/Components/SearchFilters/LanguageFilter/__snapshots__/LanguageFilter.test.jsx.snap
  src/Components/SearchFilters/MultiSelectFilter/__snapshots__/MultiSelectFilter.test.jsx.snap
  src/Components/SearchFilters/PostFilter/__snapshots__/PostFilter.test.jsx.snap
  src/Components/SearchFilters/SkillFilter/__snapshots__/SkillFilter.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/Containers/BidderPortfolio/BidderPortfolio.jsx
  src/Containers/ProfilePublic/ProfilePublic.jsx
  src/actions/assignmentMaintenance.js
  src/reducers/assignmentMaintenance/assignmentMaintenance.js
  src/reducers/assignmentMaintenance/assignmentMaintenance.test.js
  src/reducers/assignmentMaintenance/index.js
  src/reducers/index.js
  src/sass/_common.scss
  src/sass/_positionContent.scss
  src/sass/_positionSearch.scss
  src/sass/_spinner.scss
  src/utilities.js
Labels: Approved :heavy_check_mark:, size/XXL

#2683 hotfix orgs
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2685 naming
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2688 add loading spinner while filters load - adjust table names
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
  src/sass/_spinner.scss
Labels: Approved :heavy_check_mark:, size/L

#2692 Update for edit
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/actions/remark.js
  src/sass/_common.scss
Labels: dual merge, size/M, Approved :heavy_check_mark:

#2681 [TM-4914] Org Stats
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/OrgStats/OrgStats.jsx
  src/Components/AdministratorPage/OrgStats/OrgStatsCard.jsx
  src/Components/AdministratorPage/OrgStats/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/actions/orgStats.js
  src/reducers/index.js
  src/reducers/orgStats/index.js
  src/reducers/orgStats/orgStats.js
  src/sass/_common.scss
  src/sass/_positionContent.scss
  src/sass/_tabbedCard.scss
Labels: Approved :heavy_check_mark:, feature, size/XL

#2694 Fix ri minus button
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
Labels: size/M, Approved :heavy_check_mark:, fix

#2693 TM-4707: Feature/admin job categories
  public/config/config.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/JobCategories/JobCategories.jsx
  src/Components/AdministratorPage/JobCategories/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/actions/cycleManagement.js
  src/actions/jobCategories.js
  src/reducers/index.js
  src/reducers/jobCategories/index.js
  src/reducers/jobCategories/jobCategories.js
  src/sass/_jobCategoriesAdmin.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, feature, size/L

#2684 [TM-4913] Manage Entry Level Positions
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/ManageEntryLevel/EntryLevelCard.jsx
  src/Components/AdministratorPage/ManageEntryLevel/ManageEntryLevel.jsx
  src/Components/Assignments/AssignmentCard/AssignmentCard.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.test.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/actions/entryLevel.js
  src/reducers/entryLevel/entryLevel.js
  src/reducers/entryLevel/index.js
  src/reducers/index.js
  src/sass/_datePicker.scss
  src/sass/_filters.scss
  src/sass/_positionContent.scss
  src/sass/_variables.scss
Labels: Approved :heavy_check_mark:, size/XXL, feature

#2696 [TM-4914] Org Stats Fix Definition Label
  src/Components/AdministratorPage/OrgStats/OrgStats.jsx
  src/Components/AdministratorPage/OrgStats/OrgStatsCard.jsx
Labels: size/XS, fix

#2682 TM-4834-Bureau-Exception-List
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
  src/Components/AdministratorPage/BureauExceptionList/BureauExceptionListCard.jsx
  src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
  src/Components/AdministratorPage/BureauExceptionList/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/actions/bureauException.js
  src/reducers/bureauException/bureauException.js
  src/reducers/bureauException/index.js
  src/reducers/index.js
  src/sass/_bureauExceptionList.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, size/XL

#2695 TM-4707: Job Categories Follow-up
  src/Components/AdministratorPage/JobCategories/JobCategories.jsx
  src/sass/_jobCategoriesAdmin.scss
Labels: Approved :heavy_check_mark:, size/XS

#2698 [TM-4913] Manage Entry Level Positions Reset Form
  src/Components/AdministratorPage/ManageEntryLevel/EntryLevelCard.jsx
Labels: Approved :heavy_check_mark:, size/XS, fix

#2699 BugFix-CSS
  src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
  src/sass/_bureauExceptionList.scss
Labels: Approved :heavy_check_mark:, size/S

#2678 TM-4735-CDO-D3.0
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioCardList/__snapshots__/BidderPortfolioCardList.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.test.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatCard/__snapshots__/BidderPortfolioStatCard.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.test.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/__snapshots__/BidderPortfolioStatRow.test.jsx.snap
  src/Components/Ribbon/Cusp/Cusp.jsx
  src/Components/Ribbon/Cusp/index.js
  src/Components/Ribbon/Eligible/Eligible.jsx
  src/Components/Ribbon/Eligible/index.js
  src/Components/Ribbon/index.js
  src/Constants/Sort.js
  src/Constants/SystemMessages.js
  src/actions/bidderPortfolio.js
  src/sass/_bidderPortfolio.scss
Labels: Approved :heavy_check_mark:, size/XXL

#2700 TM-4834-BureauExceptionList-Pt-II
  src/Components/AdministratorPage/BureauExceptionList/BureauExceptionListCard.jsx
  src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
  src/actions/bureauException.js
  src/sass/_bureauExceptionList.scss
Labels: Approved :heavy_check_mark:, size/L

#2701 disable posnum on Edit mode and adjust text limit
  src/Components/BureauPage/PositionManager/PositionManagerSearch/PositionManagerSearch.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
Labels: Approved :heavy_check_mark:, size/XS, fix

#2702 Release/11.1
  public/config/config.json
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Constants/Menu.js
  src/Constants/Sort.js
Labels: size/M

#2704 Update version and 2000 limit
  package.json
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2691 TM-4833-UI-Assignment-Cycles
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/AssignmentCycles/AssignmentCycles.jsx
  src/Components/AdministratorPage/AssignmentCycles/AssignmentCyclesCard.jsx
  src/Components/AdministratorPage/AssignmentCycles/NewAssignmentCycle.jsx
  src/Components/AdministratorPage/AssignmentCycles/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/actions/assignmentCycle.js
  src/reducers/assignmentCycle/assignmentCycle.js
  src/reducers/assignmentCycle/index.js
  src/reducers/index.js
  src/sass/_assignmentCycles.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, size/XXL

#2706 Fix bureau routes
  src/Components/BureauPage/BureauPage.jsx
Labels: Approved :heavy_check_mark:, size/XS, fix

#2709 Fix/bad merge conflict
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatCard/__snapshots__/BidderPortfolioStatCard.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/__snapshots__/BidderPortfolioStatRow.test.jsx.snap
  src/actions/assignment.js
Labels: size/S, fix

#2711 Do not persist text area onCancel
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: size/XS, fix

#2697 [TM-4832] Cycle Job Category
  public/config/config.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/AssignmentCycles/AssignmentCyclesCard.jsx
  src/Components/AdministratorPage/AssignmentCycles/NewAssignmentCycle.jsx
  src/Components/AdministratorPage/CycleJobCategories/CycleJobCategories.jsx
  src/Components/AdministratorPage/CycleJobCategories/index.js
  src/Components/AdministratorPage/JobCategories/JobCategories.jsx
  src/Components/CheckBox/CheckBox.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/actions/cycleJobCategories.js
  src/reducers/cycleJobCategories/cycleJobCategories.js
  src/reducers/cycleJobCategories/index.js
  src/reducers/index.js
  src/sass/_cycleJobCategory.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, size/XL, 9.30

#2707 [TM-4830] TM1 Notification
  src/Components/Assignments/NotificationCard/Common/InputActions.jsx
  src/Components/Assignments/NotificationCard/NotificationCard.jsx
  src/Components/Assignments/NotificationCard/Tabs/Assignments.jsx
  src/Components/Assignments/NotificationCard/Tabs/EFM.jsx
  src/Components/Assignments/NotificationCard/Tabs/Header.jsx
  src/Components/Assignments/NotificationCard/Tabs/Paragraphs.jsx
  src/Components/Assignments/NotificationCard/Tabs/Remarks.jsx
  src/Components/Assignments/NotificationCard/Tabs/Routing.jsx
  src/Components/Assignments/NotificationCard/Tabs/Training.jsx
  src/Components/Assignments/NotificationCard/index.js
  src/Components/Notifications/Notifications.jsx
  src/sass/_notificationCard.scss
  src/sass/_positionContent.scss
  src/sass/styles.scss
Labels: feature, size/XL, 9.30

#2716 Feature Flag Cycle Job Categories and Job Categories
  src/Components/AdministratorPage/AssignmentCycles/AssignmentCyclesCard.jsx
  src/Components/AdministratorPage/AssignmentCycles/NewAssignmentCycle.jsx
  src/Components/AdministratorPage/CycleJobCategories/CycleJobCategories.jsx
Labels: Approved :heavy_check_mark:, size/S

#2710 TM-4966, Publishable Position Ui
  public/config/config.json
  public/config/config_dev.json
  src/Components/Assignments/NotificationCard/Tabs/Assignments.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
Labels: Approved :heavy_check_mark:, size/L, 9.30

#2712 Feature/tm1 memo 2
  public/config/config.json
  src/Components/Assignments/AssignmentCard/AssignmentCard.jsx
  src/Components/Assignments/Assignments.jsx
  src/Components/Assignments/NotificationCard/NotificationCard.jsx
  src/Components/Assignments/NotificationCard/Tabs/Header.jsx
  src/Components/Assignments/NotificationCard/Tabs/Memo.jsx
  src/Components/Assignments/NotificationCard/Tabs/MemoHeader.jsx
  src/Components/Assignments/NotificationCard/Tabs/Paragraphs.jsx
  src/Components/Assignments/NotificationCard/Tabs/Routing.jsx
  src/Components/Notifications/Notifications.jsx
  src/Constants/Menu.js
  src/sass/_common.scss
  src/sass/_notificationCard.scss
  src/sass/_positionContent.scss
  src/sass/_positionSearch.scss
Labels: feature, size/XL, 9.30

#2705 [TM-4915] Bidding Tool
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AoPage/AoPage.jsx
  src/Components/BiddingFunctionsPage/BiddingFunctionsPage.jsx
  src/Components/BiddingFunctionsPage/BiddingFunctionsPage.test.jsx
  src/Components/BiddingFunctionsPage/BiddingFunctionsPageLoadable.jsx
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingTool.jsx
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/index.js
  src/Components/BiddingFunctionsPage/BiddingTool/index.js
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/PostPage/PostPage.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/ProfilePage/ProfilePage.jsx
  src/Constants/Menu.js
  src/Constants/SystemMessages.js
  src/actions/biddingTool.js
  src/reducers/biddingTool/biddingTool.js
  src/reducers/biddingTool/index.js
  src/reducers/index.js
  src/sass/_biddingTool.scss
  src/sass/_common.scss
  src/sass/styles.scss
  yarn.lock
Labels: Approved :heavy_check_mark:, size/XXL, 9.30

#2708 TM-4846: Job Categories Save/Edit Integration
  src/Components/AdministratorPage/JobCategories/CreateJobCategoryModal.jsx
  src/Components/AdministratorPage/JobCategories/JobCategories.jsx
  src/Constants/SystemMessages.js
  src/actions/jobCategories.js
  src/reducers/jobCategories/index.js
  src/reducers/jobCategories/jobCategories.js
  src/sass/_jobCategoriesAdmin.scss
Labels: size/XL, 9.30

#2719 PP Classifications Hotfix
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingTool.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/actions/biddingTool.js
Labels: size/M

#2717 TM-Cycle-Management/Assignment-Cycles
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/AssignmentCycles/AssignmentCycles.jsx
  src/Components/AdministratorPage/AssignmentCycles/AssignmentCyclesCard.jsx
  src/Components/AdministratorPage/AssignmentCycles/index.js
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/Components/CycleManagement/EditAssignmentCycles.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/actions/assignmentCycle.js
  src/actions/cycleManagement.js
  src/reducers/assignmentCycle/assignmentCycle.js
  src/reducers/assignmentCycle/index.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
  src/reducers/index.js
  src/sass/_assignmentCycles.scss
  src/sass/_filters.scss
  src/sass/_positionSearch.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, size/XXL, 9.30

#2713 TM-4916-Bid-Audit
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditModal.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditSections/BidAuditSections.jsx
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/Constants/Sort.js
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
  src/reducers/index.js
  src/sass/_bidAudit.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: WIP, Approved :heavy_check_mark:, size/XXL, 9.30

#2723 Wording
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditModal.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2722 TM-Cycle-Management-Assignment-Scroll
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/Components/CycleManagement/EditAssignmentCycles.jsx
  src/sass/_modal.scss
  src/sass/_positionSearch.scss
Labels: size/M, Approved :heavy_check_mark:

#2724 TM-Bid-Audit-UI
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditModal.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditSections/BidAuditSections.jsx
  src/actions/bidAudit.js
  src/sass/_bidAudit.scss
Labels: size/XL
