Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-02, with the labels that each got.

#2443 ending slash for url
  src/actions/panelMeetingAgendas.js
Labels: dual merge, approved, size/XS, fix

#2442 TM-3907 align eas boxes
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/sass/_employeeSearch.scss
Labels: approved, size/L, fix

#2447 TM-3680 Update/panel meetings
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Components/Panel/PanelMeetingSearchRow/__snapshots__/PanelMeetingSearchRow.test.jsx.snap
  src/Constants/PropTypes.js
  src/actions/panelMeetings.js
  src/sass/_panelSearch.scss
Labels: approved, size/XL

#2454 TM-3763 remove official from panel meeting row
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
Labels: approved, size/XS, fix

#2448 Add authn to IDP and SP
  src/saml2-config.alt.js
  src/saml2-config.js
Labels: approved, size/XS, fix

#2462 TM-3958: Fixing results controls spacing at lower resolutions
  src/sass/_employeeSearch.scss
Labels: approved, size/XS, fix

#2458 sorts for Panel Meetings and removing unused textInput
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Constants/Sort.js
Labels: dual merge, approved, size/XS

#2464 updating call
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: size/XS, fix

#2449 TM-2999 - Position Search Sticky Filters
  public/assets/img/tandem_search_toggle.png
  src/Components/ResultsContainer/ResultsContainer.jsx
  src/Components/ResultsContainer/__snapshots__/ResultsContainer.test.jsx.snap
  src/Components/ResultsFilterContainer/ResultsFilterContainer.jsx
  src/Components/ResultsFilterContainer/ResultsFilterContainer.test.jsx
  src/Components/ResultsFilterContainer/__snapshots__/ResultsFilterContainer.test.jsx.snap
  src/Components/ResultsPage/tutorialSteps.js
  src/sass/_clientView.scss
  src/sass/_results.scss
Labels: approved, size/XXL, feature

#2455 styling updates
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/sass/_agendaItemMaintenance.scss
Labels: approved, size/S

#2467 small text size fix for TM-2999
  src/sass/_clientView.scss
Labels: approved, size/XS, fix

#2471 change display sooner
  src/sass/_employeeSearch.scss
Labels: size/XS, fix

#2469 Feature/pmi official item number TM-4003
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_panelMeetingAgendas.scss
Labels: dual merge, size/M, approved, feature

#2465 Feature/pm agenda filters TM-3927
  package.json
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/FrequentPositions.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/BidTracker/BidStep/__snapshots__/BidSteps.test.jsx.snap
  src/Components/Glossary/Glossary.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/sass/_panelMeetingAgendas.scss
  src/utilities.js
  yarn.lock
Labels: approved, feature, size/L

#2416 assignment hist tab integration aim TM-2768
  src/Components/ProfileDashboard/Assignments/AssignmentsListResultsCard/AssignmentsContent/AssignmentsContent.jsx
  src/Components/ProfileDashboard/Assignments/AssignmentsListResultsCard/AssignmentsContent/__snapshots__/AssignmentsContent.test.jsx.snap
Labels: dual merge, approved, size/S

#2475 Fix initial loading state
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: approved, size/XS, fix

#2473 Panel Meetings Tracker TM-4025
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Components/Panel/PanelMeetingSearchRow/__snapshots__/PanelMeetingSearchRow.test.jsx.snap
  src/Components/Panel/helpers.js
  src/Components/Tracker/Tracker.jsx
  src/Components/Tracker/index.js
  src/Constants/PropTypes.js
  src/sass/_panelSearch.scss
  src/sass/_tracker.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: approved, feature, size/XL

#2472 TM-3952: Panel Meetings Export
  src/actions/panelMeetings.js
Labels: approved, size/XS

#2470 panel meeting search pagination TM-4024
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
Labels: dual merge, size/M, approved, Approved Pending Feedback

#2474 TM-3951 Feature/pma all dates
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Components/Panel/PanelMeetingSearchRow/__snapshots__/PanelMeetingSearchRow.test.jsx.snap
  src/Components/Panel/PanelMeetingTracker/PanelMeetingTracker.jsx
  src/Components/Panel/PanelMeetingTracker/PanelMeetingTracker.test.jsx
  src/Components/Panel/PanelMeetingTracker/__snapshots__/PanelMeetingTracker.test.jsx.snap
  src/Components/Panel/PanelMeetingTracker/index.js
  src/sass/_panelMeetingAgendas.scss
  src/sass/_panelMeetingTracker.scss
  src/sass/_panelSearch.scss
  src/sass/styles.scss
Labels: approved, feature, size/L
