Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-06, with the labels that each got.

#2573 TM-4090: Edit panel meeting functionality
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.test.jsx
  src/Components/Panel/PanelMeetingSearchRow/__snapshots__/PanelMeetingSearchRow.test.jsx.snap
  src/actions/panelMeetingAdmin.js
  src/actions/panelMeetingAgendas.js
  src/hooks.js
  src/reducers/panelMeetingAgendas/index.js
  src/reducers/panelMeetingAgendas/panelMeetingAgendas.js
  src/sass/_panelAdmin.scss
  src/sass/_panelSearch.scss
Labels: Approved :heavy_check_mark:, size/L

#2582 TM-4116: fixing EP for new create remark functionality
  src/actions/editRemark.js
Labels: Approved :heavy_check_mark:, size/XS, fix

#2583 TM-4444, TM-4437, TM-4537, handle other tod
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/sass/_agendaItemLegsForm.scss
Labels: aging :older_adult:, Approved :heavy_check_mark:, size/L

#2586 remove panel meeting default on create
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2578 removing unused code
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/actions/panelMeetingAgendas.js
  src/reducers/panelMeetingAgendas/index.js
  src/reducers/panelMeetingAgendas/panelMeetingAgendas.js
Labels: size/M, Approved :heavy_check_mark:

#2591 Revert "removing unused code"
  src/actions/panelMeetingAgendas.js
  src/reducers/panelMeetingAgendas/panelMeetingAgendas.js
Labels: size/M

#2588 [TM-4568] Remaining Typescript Utilities
  package.json
  src/types.d.ts
  src/utilities.test.ts
  src/utilities.tsx
  yarn.lock
Labels: Approved :heavy_check_mark:, size/XXL

#2590 TM-4306, add Vice/Vacancy to AIs
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemRow.scss
Labels: Approved :heavy_check_mark:, size/S

#2585 TM-4046 read only version of AIM form
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsForm.test.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsFormReadOnly/index.js
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/actions/agendaItemMaintenancePane.js
  src/sass/_agendaItemLegsFormReadOnly.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, feature, size/XL

#2589 TM-4562: refactoring so that panelmeetingadmin loads panel meeting data indepe…
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/actions/panelMeetingAdmin.js
  src/actions/panelMeetingAgendas.js
  src/reducers/panelMeetingAgendas/index.js
  src/reducers/panelMeetingAgendas/panelMeetingAgendas.js
  src/sass/_panelAdmin.scss
Labels: Approved :heavy_check_mark:, size/L, Approved Pending Feedback :stopwatch:

#2587 [TM-4568/4569] Converted Utilities from JS to TS
  package.json
  src/Components/MediaQuery/MediaQuery.tsx
  src/types.d.ts
  src/utilities.test.ts
  src/utilities.tsx
  tsconfig.json
  yarn.lock
Labels: Approved :heavy_check_mark:, size/XXL

#2592 touch up for dev data
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/Constants.js
Labels: Approved :heavy_check_mark:, size/S

#2593 TM-4562 Fix: removing extra label
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
Labels: size/XS, fix
