Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-01, with the labels that each got.

#2423 TM-3731: Client Profiles - Combine Location & Org
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatCard/__snapshots__/BidderPortfolioStatCard.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/__snapshots__/BidderPortfolioStatRow.test.jsx.snap
  src/sass/_bidderPortfolio.scss
Labels: dual merge, approved, size/S

#2420 TM-3611 feature/pma-section-header
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/actions/panelMeetingAgendas.js
  src/sass/_panelMeetingAgendas.scss
  src/sass/_panelSearch.scss
Labels: approved, feature, size/L, Approved Pending Feedback

#2421 edit position details edit TM-3707
  src/Components/EditPositionDetails/PositionDetailsCard/PositionDetailsCard.jsx
  src/Components/EditPositionDetails/PositionDetailsCard/__snapshots__/PositionDetailsCard.test.jsx.snap
  src/sass/_editPositionDetails.scss
Labels: approved, feature, size/L

#2425 TM-3734 BureauResultsCard location(org)
  src/Components/BureauPage/BureauResultsCard/BureauResultsCard.jsx
Labels: approved, size/S

#2410 tst2-updates
  package.json
  public/index.html
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/HrOnlineIFrame/HrOnlineIFrame.jsx
  src/Components/HrOnlineIFrame/index.js
  src/index.jsx
  src/utilities.js
Labels: do not merge, size/M, approved, feature

#2431 Fix/handling empty
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
Labels: approved, size/XS, fix

#2429 Panel Meetings
  src/actions/panelMeetings.js
Labels: WIP, size/XS

#2430 TM-3732 update/eas
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/sass/_employeeSearch.scss
Labels: approved, size/S

#2432 TM-3846 disable pma status dd
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
Labels: approved, size/XS

#2433 TM-3666: Splitting EAS into 3 separate search boxes
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/Components/BureauPage/PositionManager/PositionManagerSearch/PositionManagerSearch.jsx
  src/sass/_employeeSearch.scss
Labels: dual merge, approved, size/L

#2437 Add fixes
  src/Components/HrOnlineIFrame/HrOnlineIFrame.jsx
  src/index.jsx
  src/utilities.js
Labels: approved, size/XS, fix

#2428 aim read/edit ingest TM-3721
  public/config/config.json
  public/config/config_dev.json
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchCard/__snapshots__/EmployeeAgendaSearchCard.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Constants/PropTypes.js
Labels: do not merge, approved, feature, size/XL

#2436 TM-3856 Client Profile AIH link
  src/Components/ProfileDashboard/AgendaItemHistoryLink/AgendaItemHistoryLink.jsx
  src/Components/ProfileDashboard/AgendaItemHistoryLink/index.js
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Containers/ProfilePublic/ProfilePublic.jsx
  src/sass/_profile.scss
Labels: approved, size/S

#2438 TM-3869: EAS UI Toggle Active/Inactive Employees Search
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/sass/_employeeSearch.scss
Labels: dual merge, size/M, approved, feature, Approved Pending Feedback

#2441 TM-3909: Alphabetizing status dropdown on AIM page
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: approved, size/XS, fix
