Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-12, with the labels that each got.

#2773 touch up width for datepicker
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/TMDatePicker/TMDatePicker.jsx
  src/sass/_common.scss
  src/sass/_datePicker.scss
Labels: size/M, Approved :heavy_check_mark:

#2781 Update/create edit pmi
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Constants/PropTypes.js
  src/actions/agendaItemMaintenancePane.js
Labels: size/S

#2783 TM-5196: Swap Order of Speaking and Reading Language Skills
  src/Components/ProfileDashboard/Languages/Languages.jsx
  src/Components/ProfileDashboard/Languages/__snapshots__/Languages.test.jsx.snap
Labels: Approved :heavy_check_mark:, size/XS

#2786 BEL small updates
  src/Components/AdministratorPage/BureauExceptions/BureauExceptionsCard.jsx
  src/actions/bureauExceptions.js
Labels: Approved :heavy_check_mark:, size/XS

#2776 TM-5197-Panel-Agenda-User-Centric-Data
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/__snapshots__/UserProfileGeneralInformation.test.jsx.snap
  src/Components/ProfileDashboard/UserProfile/UserProfilePersonalInformation/__snapshots__/UserProfilePersonalInformation.test.jsx.snap
  src/Components/SkillCodeList/SkillCodeList.jsx
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemLegsFormReadOnly.scss
  src/sass/_agendaItemRow.scss
  src/sass/_panelMeetingAgendas.scss
  src/sass/_variables.scss
Labels: Approved :heavy_check_mark:, size/L

#2794 create & edit AI
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: size/XS

#2793 TM-5218, Create Printable Panel Agenda
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
  src/sass/_panelMeetingAgendas.scss
  src/sass/_panelMeetingTracker.scss
  src/sass/_tracker.scss
Labels: Approved :heavy_check_mark:, size/L

#2797 small fix
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2791 [TM-4919] Bidding Tool Integration
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingTool.jsx
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
  src/Constants/SystemMessages.js
  src/actions/biddingTool.js
  src/reducers/biddingTool/biddingTool.js
  src/reducers/biddingTool/index.js
  src/sass/_positionContent.scss
Labels: Approved :heavy_check_mark:, size/XXL

#2798 one more
  .eslintrc
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2799 one fix to rule them all
  .eslintrc
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2800 [TM-4919] Bidding Tool Integration Patches v1
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingTool.jsx
Labels: Approved :heavy_check_mark:, size/XS
