Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-05, with the labels that each got.

#2547 TM-2729, add modal for custom TOD input
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/TodModal.jsx
  src/sass/_agendaItemLegsForm.scss
Labels: aging :older_adult:, size/L

#2554 TM-4283, add AIM link to AIH page
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_agendaItemHistory.scss
Labels: size/M, Approved Pending Feedback :stopwatch:

#2557 Update/consolidate ai styles
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_agendaItemHistory.scss
  src/sass/_agendaItemRow.scss
  src/sass/_panelMeetingAgendas.scss
Labels: Approved :heavy_check_mark:, size/L

#2560 random edit mode
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2551 TM-4048: Remarks Glossary Wrap Up
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/__snapshots__/RemarksGlossary.test.jsx.snap
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
  src/Components/Glossary/GlossarySearch/__snapshots__/GlossarySearch.test.jsx.snap
  src/Components/SaveNewSearchDialog/__snapshots__/SaveNewSearchDialog.test.jsx.snap
  src/Components/TextInput/TextInput.jsx
  src/Components/TextInput/__snapshots__/TextInput.test.jsx.snap
  src/sass/_agendaItemMaintenance.scss
  src/utilities.js
Labels: dual merge, Approved :heavy_check_mark:, size/L

#2558 removing static content
  public/config/config.json
  src/Components/BidTracker/BidTrackerCard/BidTrackerCard.jsx
  src/Components/BidTracker/BidTrackerCardBottom/BidTrackerCardBottom.jsx
  src/Components/BidTracker/BidTrackerCardBottom/__snapshots__/BidTrackerCardBottom.test.jsx.snap
  src/Components/BidTracker/OverlayAlert/ApprovedAlert/ApprovedAlert.jsx
  src/Components/BidTracker/OverlayAlert/ApprovedAlert/__snapshots__/ApprovedAlert.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/__snapshots__/BidderPortfolioPage.test.jsx.snap
  src/Components/BidderPortfolio/EditButtons/EditButtons.jsx
  src/Components/BidderPortfolio/EditButtons/EditButtons.test.jsx
  src/Components/BidderPortfolio/EditButtons/__snapshots__/EditButtons.test.jsx.snap
  src/Components/BidderPortfolio/EditButtons/index.js
  src/Components/BidderPortfolio/TopNav/Actions/Actions.jsx
  src/Components/BidderPortfolio/TopNav/Actions/Actions.test.jsx
  src/Components/BidderPortfolio/TopNav/Actions/ActionsButton/ActionsButton.jsx
  src/Components/BidderPortfolio/TopNav/Actions/ActionsButton/ActionsButton.test.jsx
  src/Components/BidderPortfolio/TopNav/Actions/ActionsButton/__snapshots__/ActionsButton.test.jsx.snap
  src/Components/BidderPortfolio/TopNav/Actions/ActionsButton/index.js
  src/Components/BidderPortfolio/TopNav/Actions/__snapshots__/Actions.test.jsx.snap
  src/Components/BidderPortfolio/TopNav/Actions/index.js
  src/Components/CompareList/CompareList.jsx
  src/Components/CompareList/__snapshots__/CompareList.test.jsx.snap
  src/Components/Header/Header.jsx
  src/Components/Header/__snapshots__/Header.test.jsx.snap
  src/Components/PositionDetailsItem/PositionDetailsContact/PositionDetailsContact.jsx
  src/Components/PositionDetailsItem/PositionDetailsContact/__snapshots__/PositionDetailsContact.test.jsx.snap
  src/Components/ProfileDashboard/BidList/BidList.jsx
  src/Components/ProfileDashboard/BidList/__snapshots__/BidList.test.jsx.snap
  src/Components/ProfileDashboard/Favorites/FavoritesList.jsx
  src/Components/ProfileDashboard/Favorites/__snapshots__/FavoritesList.test.jsx.snap
  src/Components/ProfileDashboard/Notifications/Notifications.jsx
  src/Components/ProfileDashboard/Notifications/__snapshots__/Notifications.test.jsx.snap
  src/Components/ProfileDashboard/SavedSearches/SavedSearchesList.jsx
  src/Components/ProfileDashboard/SavedSearches/__snapshots__/SavedSearchesList.test.jsx.snap
  src/Components/ProfileDashboard/Updates/Updates.jsx
  src/Components/ProfileDashboard/UserProfile/EditProfile/EditProfile.jsx
  src/Components/ProfileDashboard/UserProfile/EditProfile/EditProfile.test.jsx
  src/Components/ProfileDashboard/UserProfile/EditProfile/__snapshots__/EditProfile.test.jsx.snap
  src/Components/ProfileDashboard/UserProfile/EditProfile/index.js
  src/Components/ProfileDashboard/UserProfile/Status/Status.jsx
  src/Components/ProfileDashboard/UserProfile/Status/Status.test.jsx
  src/Components/ProfileDashboard/UserProfile/Status/__snapshots__/Status.test.jsx.snap
  src/Components/ProfileDashboard/UserProfile/Status/index.js
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/__snapshots__/UserProfileGeneralInformation.test.jsx.snap
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/StaticDevContent/StaticDevContent.jsx
  src/Components/StaticDevContent/ToggleContent.jsx
  src/Components/StaticDevContent/index.js
  src/Constants/Menu.js
Labels: Approved :heavy_check_mark:, size/XL

#2555 Fix formatting for date
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
Labels: dual merge, Approved :heavy_check_mark:, size/XS

#2559 TM-4326, updates to handle TOD input
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/TodModal.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
Labels: size/M, Approved :heavy_check_mark:

#2564 TM-4276 AI Validation
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Constants/PropTypes.js
  src/actions/agendaItemMaintenancePane.js
  src/reducers/agendaItemMaintenancePane/agendaItemMaintenancePane.js
  src/reducers/agendaItemMaintenancePane/index.js
  src/sass/_agendaItemMaintenance.scss
  src/sass/_common.scss
  src/sass/_spinner.scss
  src/sass/styles.scss
Labels: dual merge, Approved :heavy_check_mark:, feature, size/XL

#2566 TM-4074, panel admin - create panel meeting
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AvailableBidder/EditBidder/EditBidder.jsx
  src/Components/AvailableBidder/EditBidder/__snapshots__/EditBidder.test.jsx.snap
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Constants/SystemMessages.js
  src/actions/panelMeetingAdmin.js
  src/reducers/index.js
  src/reducers/panelMeetingAdmin/createPanelMeeting.js
  src/reducers/panelMeetingAdmin/index.js
  src/sass/_availableBidders.scss
  src/sass/_datePicker.scss
  src/sass/_panelAdmin.scss
  src/sass/styles.scss
Labels: Approved :heavy_check_mark:, size/XL

#2562 TM-4082 & TM-4093: FE cleanup for admin remarks page + edit remark UI
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
  src/Components/AdministratorPage/EditRemark/EditRemark.test.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.test.jsx
  src/Constants/SystemMessages.js
  src/actions/editRemark.js
  src/reducers/editRemark/editRemark.js
  src/reducers/editRemark/index.js
  src/reducers/index.js
  src/sass/_panelAdmin.scss
Labels: Approved :heavy_check_mark:, size/L, fix

#2574 correct EP
  src/actions/panelMeetingAdmin.js
Labels: size/S, fix

#2575 Edit Panel UI Fix - defaulting to array instead of string
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
Labels: size/XS, fix

#2568 TM-4449 Feature/ai validation legs
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Constants/PropTypes.js
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_common.scss
Labels: dual merge, Approved :heavy_check_mark:, feature, size/L

#2576 ticket link
  .github/pull_request_template.md
Labels: size/XS
