Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-04, with the labels that each got.

#2510 Clean up some console errors in agenda item history and employee agenda pages
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Constants/PropTypes.js
Labels: size/M, fix

#2511 clean up console errors Ai Maintenence
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/FrequentPositions.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/__snapshots__/RemarksGlossary.test.jsx.snap
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/BidderPortfolio/CheckboxList/CheckboxList.jsx
  src/Components/BidderPortfolio/ClientBadge/ClientBadge.jsx
  src/Components/NavTabs/NavTabs.jsx
  src/Components/ProfileDashboard/Classifications/Classifications.jsx
  src/Components/ProfileDashboard/Languages/Languages.jsx
  src/Constants/PropTypes.js
Labels: size/L, fix

#2532 TM-4241, fix search toggling
  src/Components/ResultsContainer/ResultsContainer.jsx
  src/Components/ResultsFilterContainer/ResultsFilterContainer.jsx
  src/Components/ResultsFilterContainer/__snapshots__/ResultsFilterContainer.test.jsx.snap
  src/Components/ResultsPage/ResultsPage.jsx
Labels: approved, size/S

#2530 TM-4196: moving clear filters to above inactive toggle
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/sass/_employeeSearch.scss
  src/sass/_filters.scss
  src/sass/_profile.scss
Labels: approved, size/S, fix, Approved Pending Feedback

#2519 Add eslint react hook rules
  .eslintrc
  package.json
  src/Components/BidTracker/OverlayAlert/TimeRemaining/TimeRemaining.tsx
  yarn.lock
Labels: Approved :heavy_check_mark:, size/S

#2546 Add cdo filter and read logic for PMA
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: dual merge, Release, Approved :heavy_check_mark:, size/XS

#2545 TM-4297 updating contact email
  src/Components/Footer/Footer.jsx
  src/Components/Footer/__snapshots__/Footer.test.jsx.snap
Labels: Release, Approved :heavy_check_mark:, size/XS

#2535 TM-4082: Remarks Admin Page + Edit Remark Modal FE Only
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
  src/Components/AdministratorPage/EditRemark/EditRemark.test.jsx
  src/Components/AdministratorPage/EditRemark/index.js
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.test.jsx
  src/Components/AdministratorPage/PanelAdmin/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
  src/sass/_panelAdmin.scss
  src/sass/_spinner.scss
  src/sass/styles.scss
Labels: feature, size/XL

#2541 TM-4264, add fallback for AIM name
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
Labels: dual merge, aging :older_adult:, Approved :heavy_check_mark:, size/S

#2553 TM-4082: Update/admin remarks insertion removal
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
Labels: Approved :heavy_check_mark:, size/XS
