Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2023-10, with the labels that each got.

#2671 TM-4894 emp profile to api call
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileModal.jsx
  src/actions/availableBidders.js
  src/actions/userProfilePublic.js
Labels: do not merge, dual merge, size/M, Approved :heavy_check_mark:

#2687 TM-4848 manage post access api
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
  src/Components/ManagePostAccess/ManagePostAccess.jsx
  src/actions/managePostAccess.js
  src/reducers/managePostAccess/index.js
  src/reducers/managePostAccess/managePostAccess.js
  src/sass/_postAccess.scss
  src/sass/_variables.scss
Labels: Approved :heavy_check_mark:, size/XL

#2728 HOTFIX - Search Post Access Page CSS Fix
  src/sass/_postAccess.scss
Labels: Approved :heavy_check_mark:, size/S

#2729 tiny fix
  src/Components/ManagePostAccess/ManagePostAccess.jsx
Labels: size/XS

#2689 4683-TM Manage Bid Seasons w/ API
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/ManageBidSeasons/EditBidSeasons.jsx
  src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasons.jsx
  src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasonsCard.jsx
  src/Components/ManagePostAccess/ManagePostAccess.jsx
  src/Constants/Menu.js
  src/actions/BidSeasons.js
  src/reducers/bidSeasons/bidSeasons.js
  src/reducers/bidSeasons/index.js
  src/sass/_bidSeasons.scss
Labels: Approved :heavy_check_mark:, size/XL

#2727 Job Category Integration: Create, Edit, and Delete
  src/Components/AdministratorPage/JobCategories/CreateJobCategoryModal.jsx
  src/Components/AdministratorPage/JobCategories/JobCategories.jsx
  src/Constants/SystemMessages.js
  src/actions/jobCategories.js
  src/reducers/jobCategories/index.js
  src/reducers/jobCategories/jobCategories.js
  src/sass/_jobCategoriesAdmin.scss
  src/sass/_spinner.scss
Labels: Approved :heavy_check_mark:, size/XL

#2735 Job Categories Integration - fixing render issue
  src/Components/AdministratorPage/JobCategories/JobCategories.jsx
Labels: size/XS, fix

#2734 rollback names dumbness
  src/Components/ManagePostAccess/ManagePostAccess.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2730 TM-4980 Publishable Positions - FE Update for Future Integration
  public/config/config.json
  public/config/config_dev.json
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/Components/Spinner/Spinner.jsx
  src/Constants/Menu.js
  src/sass/_agendaItemMaintenance.scss
  src/sass/_common.scss
  src/sass/_spinner.scss
  src/sass/_variables.scss
Labels: size/L

#2736 TM-4989 Updates to EAS export and search UI
  src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
  src/actions/agendaEmployees.js
  src/actions/agendaEmployees.test.js
  src/sass/_employeeSearch.scss
Labels: Approved :heavy_check_mark:, size/S

#2738 Job Categories Integration Follow Up
  src/Components/AdministratorPage/JobCategories/CreateJobCategoryModal.jsx
  src/Components/AdministratorPage/JobCategories/JobCategories.jsx
  src/actions/jobCategories.js
  src/reducers/jobCategories/index.js
  src/reducers/jobCategories/jobCategories.js
Labels: fix, size/XL

#2745 TM-2493, TM-4998, add combined TOD field to agenda item maintenance
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_agendaItemMaintenance.scss
  src/sass/_agendaItemRow.scss
Labels: size/M

#2739 [TM-4843] Run Panel Integration
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
  src/Components/Panel/helpers.js
  src/actions/panelMeetingAdmin.js
  src/actions/panelMeetings.js
  src/actions/postPanelProcessing.js
  src/reducers/panelMeetingAdmin/createPanelMeeting.js
  src/reducers/panelMeetingAdmin/index.js
  src/reducers/panelMeetingAdmin/panelMeetingAdmin.js
  src/reducers/panelMeetings/index.js
  src/reducers/panelMeetings/panelMeetings.js
  src/reducers/postPanelProcessing/index.js
  src/reducers/postPanelProcessing/postPanelProcessing.js
  src/sass/_positionContent.scss
Labels: Approved :heavy_check_mark:, size/XL
