Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-04, with the labels that each got.

#2931 Manage EL Checkboxes - Change to Transparent Checkboxes
  src/Components/AdministratorPage/ManageEntryLevel/EntryLevelCard.jsx
Labels: Approved, size/XS

#2916 Release 12.1
  package.json
Labels: Approved, size/XS

#2942 char counts and max rows to bid audit description text box
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditModal.jsx
Labels: Approved, size/XS

#2934 field changes for Publishable Positions
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/utilities.js
Labels: Approved, size/S

#2938 PP/Grade standardization
  .github/workflows/pr-labeler.yml
  src/Components/Agenda/AIMLegsFormRead/AIMLegsFormRead.jsx
  src/Components/Agenda/AIMLegsFormRead/__snapshots__/AIMLegsFormRead.test.jsx.snap
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaLegFormEdit/AgendaLegFormEdit.jsx
  src/Components/Agenda/AgendaLegFormEdit/__snapshots__/AgendaLegFormEdit.test.jsx.snap
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/utilities.js
Labels: do not merge, size/M, Approved

#2936 [TM-5289] Position Classifications Bug
  src/Components/AdministratorPage/OrgStats/OrgStatsCard.jsx
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
  src/Components/BureauPage/PositionManager/PositionManagerSearch/PositionManagerSearch.jsx
  src/Components/PublishablePositionCard/PositionClassification/PositionClassification.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/actions/positionClassifications.js
  src/hooks.js
  src/reducers/index.js
  src/reducers/positionClassifications/index.js
  src/reducers/positionClassifications/positionClassifications.js
  src/reducers/positionClassifications/positionClassifications.test.js
  src/sass/_positionContent.scss
Labels: Approved, size/XL

#2927 [TM-5710] Projected Vacancy Integration Remediation
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/sass/_positionContent.scss
  src/sass/_positionSearch.scss
Labels: size/M, Approved

#2939 TM-5807, cycle date classifications
  src/Components/AoPage/AoPage.jsx
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CycleManagement/CycleClassifications.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/index.js
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
Labels: Approved, size/L

#2937 Create Assignment Modal
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Assignments/AssignmentCard/AssignmentCard.jsx
  src/Components/Assignments/AssignmentModal/AssignmentModal.jsx
  src/Components/Assignments/AssignmentModal/index.js
  src/Components/Assignments/Assignments.jsx
  src/Components/MonthYearInput/MonthYearInput.jsx
  src/Components/MonthYearInput/index.js
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ReactPortal/ReactPortal.jsx
  src/Components/ReactPortal/index.js
  src/actions/assignment.js
  src/actions/positions.js
  src/hooks.js
  src/sass/_modal.scss
Labels: Approved, size/XL

#2947 testing
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: size/XS

#2948 Revert "testing"
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: size/XS

#2953 TM-4995: PP export redo
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/actions/publishablePositions.js
Labels: Approved, size/S

#2955 [TM-5710] Projected Vacancy Edit Description Fix
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
Labels: Approved, size/XS

#2958 [TM-5710] Projected Vacancy Edit Description Fix
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
Labels: Approved, size/XS

#2950 TM-5672 update cycle date classifications
  .eslintrc
  src/Components/CycleManagement/CycleClassifications.jsx
  src/Constants/SystemMessages.js
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
  src/sass/_positionSearch.scss
Labels: Approved, size/XL

#2954 [TM-5701-5702] Assignment Separations UI (Create/Edit)
  src/Components/AoPage/AoPage.jsx
  src/Components/Assignments/AssignmentCard/index.js
  src/Components/Assignments/AssignmentModal/AssignmentModal.jsx
  src/Components/Assignments/AssignmentModal/index.js
  src/Components/Assignments/index.js
  src/Components/AssignmentsSeparations/Assignment/Assignment.jsx
  src/Components/AssignmentsSeparations/Assignment/Assignment.test.jsx
  src/Components/AssignmentsSeparations/Assignment/index.js
  src/Components/AssignmentsSeparations/AssignmentsSeparations.jsx
  src/Components/AssignmentsSeparations/AssignmentsSeparations.test.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Common/InputActions.jsx
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Assignments.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/EFM.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Header.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Memo.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/MemoHeader.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Paragraphs.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Remarks.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Routing.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Training.jsx
  src/Components/AssignmentsSeparations/NotificationCard/index.js
  src/Components/AssignmentsSeparations/Separation/Separation.jsx
  src/Components/AssignmentsSeparations/Separation/Separation.test.jsx
  src/Components/AssignmentsSeparations/Separation/index.js
  src/Components/AssignmentsSeparations/__snapshots__/AssignmentsSeparations.test.jsx.snap
  src/Components/AssignmentsSeparations/index.js
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProfileDashboard/Assignments/AssignmentsList.jsx
  src/Components/ReactModal/ReactModal.jsx
  src/Components/ReactModal/index.js
  src/Components/TMDatePicker/TMDatePicker.jsx
  src/Components/TabbedCard/TabbedCard.jsx
  src/actions/assignment.js
  src/reducers/assignment/assignment.js
  src/reducers/assignment/index.js
  src/sass/_assignments.scss
  src/sass/_common.scss
  src/sass/_datePicker.scss
  src/sass/_modal.scss
  src/sass/_positionContent.scss
  src/sass/_positionSearch.scss
  src/sass/styles.scss
Labels: Approved, size/XXL

#2956 TM-5848, TM-5781, TM-5875 - Rework Bid Audit Ui
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCategory.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGrade.jsx
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
Labels: Approved, size/XXL

#2965 TM-5874, Run Bid Audit
  .eslintrc
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/actions/bidAudit.js
Labels: size/M, Approved
