Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-08, with the labels that each got.

#3066 TM1 Notification Bug Fixes
  public/config/config.json
  public/config/config_dev.json
  src/Components/AssignmentsSeparations/AssignmentsSeparations.jsx
  src/actions/assignmentNotifications.js
  src/sass/_positionContent.scss
Labels: Approved, size/XS

#3068 Tm 6363 filter bureau filter by bureau permissions in publishable positions
  src/Components/PublishablePositions/PublishablePositions.jsx
Labels: Approved, size/S

#3069 Tm 6395 filter bureau filter by bureau permissions in projected vacancy mgmt
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
Labels: Approved, size/S

#3071 TM-6372, update pv count variable
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
Labels: size/XS

#3067 TM-5919, Bid Book Ui
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditData.jsx
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
  src/sass/_bidAudit.scss
Labels: Approved, size/XL

#3074 Tm 6408 update remark text in remark pill
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
Labels: Approved, size/S

#3072 [TM-6371] Publishable Positions and Projected Vacancies Timestamps
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: Approved, size/S

#3079 Cheerio Hotfix
  package.json
Labels: Approved, size/XS

#3073 [TM-6357] TM1 Memo - Select Assignments to Add Memo
  src/Components/AoPage/AoPage.jsx
  src/Components/AssignmentsSeparations/AssignmentNotification/AssignmentNotification.jsx
  src/Components/AssignmentsSeparations/AssignmentsSeparations.jsx
  src/Constants/SystemMessages.js
  src/actions/assignmentNotifications.js
Labels: size/M, Approved

#3075 [TM-6358] TM1 Memo - Preview Card
  src/Components/AssignmentsSeparations/AssignmentNotification/AssignmentNotification.jsx
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Memo.jsx
  src/Components/TabbedCard/TabbedCard.jsx
  src/sass/_notificationCard.scss
Labels: Approved, size/L

#3076 [TM-6335] TM1 Notification - Fix Rebuild Tab
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
Labels: Approved, size/XS

#3078 TM-6148, Bid Audit Data - HTF
  src/Components/AdministratorPage/bidAudit/BidAuditData.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditHTFModal.jsx
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
  src/sass/_bidAudit.scss
Labels: size/L

#3080 [TM-6371] Projected Vacancy - Edit Update Timestamp Fix
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
Labels: size/XS

#3077 TM-4844-CDO-UI
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/actions/bidderPortfolio.js
Labels: Approved, size/S

#3070 Tm 6396 UI integration for panel remarks
  src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/RemarksPill/RemarksPill.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/Constants/PropTypes.js
Labels: Approved, size/S

#3081 [TM-6371] Projected Vacancy Update Date Fix
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
Labels: Approved, size/XS

#3084 6147 tm bid book mds
  src/Components/AdministratorPage/bidAudit/BidAuditData.jsx
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
  src/sass/_bidAudit.scss
Labels: size/XL

#3086 change filter count req
  src/Components/AdministratorPage/bidAudit/BidAuditData.jsx
Labels: size/XS

#3087 update version
  package.json
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
Labels: Approved, size/S

#3090 [TM 6310] TM1 Memo Read Edit Tabs and Rebuild Edit Tabs
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/MemoHeader.jsx
Labels: Approved, size/S

#3091 TM-6348-DETO-RWA-Bidder-Position-Searches-Integration
  src/Components/PositionDetailsItem/PositionDetailsItem.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/Ribbon/RWADeto/RWADetoRibbon.jsx
  src/Components/Ribbon/RWADeto/index.js
  src/Components/Ribbon/index.js
  src/Constants/EndpointParams.js
  src/sass/_ribbon.scss
Labels: Approved, size/S

#3092 Revert "TM-6348-DETO-RWA-Bidder-Position-Searches-Integration"
  src/Components/PositionDetailsItem/PositionDetailsItem.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/Ribbon/RWADeto/RWADetoRibbon.jsx
  src/Components/Ribbon/RWADeto/index.js
  src/Components/Ribbon/index.js
  src/Constants/EndpointParams.js
  src/sass/_ribbon.scss
Labels: Approved, size/S

#3093 Revert "Revert "TM-6348-DETO-RWA-Bidder-Position-Searches-Integration""
  src/Components/PositionDetailsItem/PositionDetailsItem.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/Ribbon/RWADeto/RWADetoRibbon.jsx
  src/Components/Ribbon/RWADeto/index.js
  src/Components/Ribbon/index.js
  src/Constants/EndpointParams.js
  src/sass/_ribbon.scss
Labels: Approved, size/S
