Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-10, with the labels that each got.

#3108 Tm 6433 re work panel meeting agendas page
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/actions/panelMeetingAgendas.js
Labels: Approved, size/L

#3110 updated .gitignore
  .gitignore
Labels: Approved, size/XS

#3114 CSS updates
  src/sass/_agendaItemRow.scss
  src/sass/_panelMeetingAgendas.scss
  src/sass/_remarks.scss
Labels: Approved, size/XS

#3115 TM-6581-UI-Email-Comments
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Constants/Sort.js
  src/actions/bidderPortfolio.js
Labels: size/M, Approved

#3112 TM1 Notification/Memo Refactor
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Preview/Preview.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/NoteHeader.jsx
Labels: Approved, size/XL

#3113 [TM-6361-6362] TM1 Generate PDF
  package.json
  public/assets/img/dos-seal-pdf.png
  public/config/config_dev.json
  src/Components/AssignmentsSeparations/NotificationCard/Preview/Preview.jsx
  yarn.lock
Labels: Approved, size/L

#3044 Update .gitignore
  .gitignore
Labels: Approved, size/XS

#3117 TM-6510-CDO D3.0 (Panel Clients & Classifications) - UI
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
  src/Components/BidderPortfolio/BidControls/BidControls.test.jsx
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/__snapshots__/BidderPortfolioPage.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Containers/BidderPortfolio/BidderPortfolio.jsx
  src/actions/bidderPortfolio.js
  src/reducers/bidderPortfolio/bidderPortfolio.js
  src/reducers/bidderPortfolio/index.js
Labels: Approved, size/XL

#3118 Client links
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
Labels: Approved, size/S

#3119 [TM-6665] TM1 Note Edit Date Bug
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
Labels: Approved, size/XS

#3122 [TM-6665] TM1 Note - Allow Individual Field Clearing
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/NoteHeader.jsx
Labels: Approved, size/XS

#3121 [TM-6612] TM1 Notification - Generate SOAP XML
  src/Components/AssignmentsSeparations/NotificationCard/Common/Utilities.js
Labels: Approved, size/S

#3124 TM-6403-CDO-Table-UI
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPorfolioTable/BidPortfolioTable.jsx
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx
  src/Constants/Sort.js
  src/Containers/BidderPortfolio/BidderPortfolio.jsx
  src/actions/bidderPortfolio.js
  src/reducers/bidderPortfolio/bidderPortfolio.js
  src/reducers/bidderPortfolio/index.js
Labels: Approved, size/L

#3125 Tm 6618 update ability to filter panel meeting agendas UI
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: size/M, Approved

#3126 Tm 6655 add ability to click checkboxes on the maintain entry level page UI
  src/Components/AgGrid/CheckBoxRenderer.js
  src/Components/EntryLevelPage/MaintainELPositions/MaintainELPositions.jsx
  src/Components/EntryLevelPage/MaintainELPositionsTable/MaintainELPositionsTable.jsx
  src/sass/_entryLevelPage.scss
Labels: size/M, Approved

#3127 add total results, remove table title
  src/Components/EntryLevelPage/MaintainELPositions/MaintainELPositions.jsx
  src/sass/_entryLevelPage.scss
Labels: Approved, size/XS

#3128 [TM-6611] TM1 Memo - Generate HTML
  src/Components/AssignmentsSeparations/NotificationCard/Common/Utilities.js
  src/Components/AssignmentsSeparations/NotificationCard/Preview/Preview.jsx
Labels: size/M, Approved

#3129 Tm 6618 update ability to filter panel meeting agendas UI
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: Approved, size/S

#3123 [TM 6614] TM1 OPS Logs
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Preview/Preview.jsx
  src/Constants/SystemMessages.js
  src/actions/assignmentNotifications.js
  src/reducers/assignmentNotifications/assignmentNotifications.js
  src/reducers/assignmentNotifications/index.js
Labels: Approved, size/XL
