Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-02, with the labels that each got.

#2849 TM-4986 Followup: Collapsible Client Profiles Filter Section
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Components/ResultsContainer/ResultsContainer.jsx
  src/Components/ResultsContainer/__snapshots__/ResultsContainer.test.jsx.snap
  src/Components/ResultsPillContainer/ResultsPillContainer.jsx
  src/Components/ResultsPillContainer/ResultsPillContainer.test.jsx
  src/Components/ResultsPillContainer/__snapshots__/ResultsPillContainer.test.jsx.snap
  src/sass/_bidderPortfolio.scss
  src/sass/_common.scss
Labels: size/M, Approved :heavy_check_mark:

#2803 [TM-4542] Employee Profile
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfile.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
  src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/__snapshots__/UserProfileGeneralInformation.test.jsx.snap
  src/Components/ProfileDashboard/UserProfile/__snapshots__/UserProfile.test.jsx.snap
  src/Containers/ProfilePublic/ProfilePublic.jsx
Labels: size/M, Approved :heavy_check_mark:

#2802 TM-5219, TM-5292, add DETO/RWA field to pub positions & position search
  public/config/config.json
  public/config/config_dev.json
  src/Components/Assignments/AssignmentCard/AssignmentCard.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/PositionDetailsItem/PositionDetailsItem.jsx
  src/Components/PositionDetailsItem/__snapshots__/PositionDetailsItem.test.jsx.snap
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
  src/Constants/EndpointParams.js
  src/reducers/filters/filters.js
Labels: size/M, Approved :heavy_check_mark:

#2850 removing redundant state updates
  src/actions/publishablePositions.js
Labels: Approved :heavy_check_mark:, size/XS

#2801 TM-5308, initial fetch and filtering for Cycle Management page
  src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasons.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
Labels: Approved :heavy_check_mark:, size/XL

#2851 HOTFIX, mapping values for Print Panel Page
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2813 TM-5413 - create new assignment cycle
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/NewAssignmentCycle.jsx
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/sass/_modal.scss
  src/sass/_positionSearch.scss
Labels: Approved :heavy_check_mark:, size/L

#2855 required fields for Create Cycle
  src/Components/CycleManagement/NewAssignmentCycle.jsx
Labels: Approved :heavy_check_mark:, size/S

#2857 Feature/maintain asg
  src/Components/Assignments/AssignmentCard/AssignmentCard.jsx
  src/Components/Assignments/Assignments.jsx
  src/Constants/SystemMessages.js
  src/actions/assignment.js
  src/reducers/assignment/assignment.js
  src/reducers/assignment/index.js
Labels: Approved :heavy_check_mark:, size/XL

#2853 [TM-4680] Projected Vacancy Integration (Read)
  src/Components/AvailableBidder/EditBidder/EditBidder.jsx
  src/Components/AvailableBidder/EditBidder/__snapshots__/EditBidder.test.jsx.snap
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/actions/projectedVacancy.js
  src/reducers/projectedVacancy/index.js
  src/reducers/projectedVacancy/projectedVacancy.js
Labels: WIP, Approved :heavy_check_mark:, size/XXL

#2863 TM-5542-AI-Validation
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2848 TM-4819-FE-Org-Stat
  src/Components/AdministratorPage/OrgStats/OrgStats.jsx
  src/Components/AdministratorPage/OrgStats/OrgStatsCard.jsx
  src/actions/orgStats.js
  src/reducers/orgStats/index.js
  src/reducers/orgStats/orgStats.js
  src/sass/_positionContent.scss
Labels: Approved :heavy_check_mark:, size/XL

#2864 TM-5561, update report category
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2870 TM-5582-Rearrange-User-Eccentric-Data
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2875 TM-5543 AIM Default Status
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: Approved ✓, size/XS

#2877 [TM-4542] Employee Profile Temporary Reversions
  src/Containers/ProfilePublic/ProfilePublic.jsx
Labels: Approved ✓, size/XS

#2874 [TM-5597] AIM Locations Search Note
  src/Components/Agenda/AgendaItemResearchPane/GsaLocations/GsaLocations.jsx
  src/sass/_agendaItemLegsForm.scss
Labels: Approved ✓, size/S

#2867 TM-5564: Update Org to "Location/Org" on AIM/Panel
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsForm/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
Labels: Approved ✓, size/S

#2862 Validation labels no text
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
Labels: dual merge, Aging :older_adult:, Approved, size/S

#2868 TM-5556 Refine Remark Inserts
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
Labels: Approved, size/S

#2879 to handle string rendering
  src/utilities.js
Labels: Approved, size/S

#2883 TM-5600-X-AIM-Tabs
  src/Components/Agenda/AgendaItemResearchPane/FrequentPositions/FrequentPositions.jsx
  src/Components/Agenda/AgendaItemResearchPane/GsaLocations/GsaLocations.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/RemarksGlossary.jsx
  src/Components/Agenda/AgendaItemResearchPane/RemarksGlossary/__snapshots__/RemarksGlossary.test.jsx.snap
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemMaintenance.scss
Labels: size/M, Approved

#2886 [TM-5597] AIM Location Search Helper Text Fix
  src/Components/Agenda/AgendaItemResearchPane/GsaLocations/GsaLocations.jsx
Labels: size/M, Approved

#2882 Update/mmyyyy ted
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/MonthYearDropdown.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/Agenda/Constants.js
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
  src/sass/_agendaItemLegsForm.scss
  src/sass/_variables.scss
  src/utilities.js
Labels: Approved, size/L

#2866 TM-5563: Combining Pay Plan and Grade on Agendas
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsForm/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemLegsFormReadOnly.scss
  src/sass/_agendaItemRow.scss
  src/sass/_variables.scss
Labels: Approved, size/L

#2887 TM-5600-X-Aim-Tabs-2
  src/sass/_agendaItemMaintenance.scss
Labels: Approved, size/XS

#2854 TM-4917: Manage EL Positions Integration
  src/Components/AdministratorPage/ManageEntryLevel/EntryLevelCard.jsx
  src/Components/AdministratorPage/ManageEntryLevel/ManageEntryLevel.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/actions/entryLevel.js
  src/reducers/entryLevel/entryLevel.js
  src/reducers/entryLevel/index.js
  src/sass/_spinner.scss
Labels: Approved, size/XL, Approved Pending Feedback

#2861 [TM-5389] Projected Vacancy Integration (Edit)
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/LanguageList/LanguageList.jsx
  src/Components/LanguageList/__snapshots__/LanguageList.test.jsx.snap
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/actions/projectedVacancy.js
  src/reducers/projectedVacancy/index.js
  src/reducers/projectedVacancy/projectedVacancy.js
  src/utilities.js
Labels: Approved, size/XL

#2872 TM-5602-Move-Action
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegs/__snapshots__/AgendaItemLegs.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsForm/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaItemLegsFormReadOnly/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemRow.scss
  src/sass/_variables.scss
Labels: Approved, size/L
