Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-01, with the labels that each got.

#2795 Setup ai success call for toggling to edit version after create - TO DO
  src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
  src/Components/Agenda/AgendaItemCard/__snapshots__/AgendaItemCard.test.jsx.snap
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
  src/Components/Agenda/EmployeeAgendaSearchRow/__snapshots__/EmployeeAgendaSearchRow.test.jsx.snap
  src/Components/AoPage/AoPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
  src/actions/agendaItemMaintenancePane.js
  src/reducers/agendaItemMaintenancePane/agendaItemMaintenancePane.js
  src/reducers/agendaItemMaintenancePane/index.js
Labels: size/XL

#2804 TM-5227/TM-5232 - Sorting
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/BureauPage/PositionManagerBidders/PositionManagerBidders.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2805 Fix default ail values with new code from api
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2806 [TM-5415] AI Create/Edit Cleanup
  src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
  src/Components/Agenda/AgendaItemLegsForm/__snapshots__/AgendaItemLegsForm.test.jsx.snap
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/Components/Agenda/AgendaLeg/__snapshots__/AgendaLeg.test.jsx.snap
  src/sass/_agendaItemLegsForm.scss
Labels: Approved :heavy_check_mark:, size/L

#2808 Make consistent read/write key for posseqnum
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
Labels: size/S

#2810 ETA should update TED field based on ETA and TOD fields
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
Labels: Approved :heavy_check_mark:, size/S

#2811 - for EF travel and action
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2814 Squeeze Print PMA
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
  src/sass/_panelMeetingAgendas.scss
  src/sass/_panelMeetingTracker.scss
Labels: Approved :heavy_check_mark:, size/S

#2819 Update panel success toast
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingMessage.jsx
  src/Constants/SystemMessages.js
  src/actions/panelMeetingAdmin.js
Labels: Approved :heavy_check_mark:, size/S

#2820 [TM-5415] AI Reload Data Bugs
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2821 On clear ensure pmt is a proper value and not desc
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2822 [TM-5456] Bug: Panel Meeting Form States Reset on Edit Save
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingMessage.jsx
  src/Components/Panel/helpers.js
  src/Constants/SystemMessages.js
  src/actions/panelMeetingAdmin.js
Labels: Approved :heavy_check_mark:, size/S

#2825 [TM-5071] Fix Run Panel Features
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
Labels: size/XS

#2824 Fix/create btn eai
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/actions/agendaItemMaintenancePane.js
Labels: size/M

#2826 TM-5457, Panel Meeting Dates, use ET and be able to read without Zulu
  src/Components/Panel/helpers.js
Labels: Approved :heavy_check_mark:, size/XS

#2828 Trying a unmount cleanup
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2831 TM-5476, check if TED is N/A before passing to formatter
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2830 Show legacy date if not in drop down
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/sass/_agendaItemMaintenance.scss
Labels: size/M, Approved :heavy_check_mark:

#2829 [TM-5071] Fix Run Panel Role Issues
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
  src/Constants/SystemMessages.js
  src/actions/panelMeetingAdmin.js
  src/sass/_positionContent.scss
Labels: size/L

#2836 [TM-5071] Post Panel: Revert Accidental Debug Change
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2834 TM-4990: Panel Meetings Missing Emp Info
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/sass/_panelMeetingAgendas.scss
Labels: dual merge, size/M, Approved :heavy_check_mark:

#2838 [TM-5071] Fix Run Panel & Post Panel Bugs
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
  src/reducers/panelMeetingAdmin/panelMeetingAdmin.js
Labels: Approved :heavy_check_mark:, size/S

#2839 TM-4990 Hotfix: Fixing PMA Filters + Removing Bureau
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
Labels: WIP, Approved :heavy_check_mark:, size/S

#2840 [TM-5071] Fix Post Panel Processing Reload Issue
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
  src/actions/postPanelProcessing.js
Labels: size/S

#2835 Change release number
  package.json
Labels: do not merge, size/XS

#2843 Create Remarks Short Descr Fix
  src/Components/AdministratorPage/EditRemark/EditRemark.jsx
  src/sass/_panelAdmin.scss
Labels: size/M

#2845 Un-nest creator/updater info
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Constants/PropTypes.js
Labels: size/XS

#2847 12.0 Release Fixes
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: size/XS

#2844 [TM-5071] Post Panel: Fix Check on Valid Agenda Items
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
Labels: Approved :heavy_check_mark:, size/XS

#2846 TM-5479, none listed vs not applicable
  src/Components/Agenda/AgendaItemLegsFormReadOnly/AgendaItemLegsFormReadOnly.jsx
  src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
  src/utilities.js
Labels: Approved :heavy_check_mark:, size/S
