Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-06, with the labels that each got.

#2996 TM-5911, TM-5914, Delete In-Category/AtGrade
  src/Components/AdministratorPage/bidAudit/BidAuditCategoryCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGradeCard.jsx
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/sass/_bidAudit.scss
Labels: size/M, Approved

#3001 [TM-6144] Maintain Assignment Post Hotfix
  src/actions/assignment.js
Labels: Approved, size/XS

#2994 TM-6048, Run Bid Audit
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCategory.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCategoryModal.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGradeModal.jsx
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/sass/_bidAudit.scss
Labels: size/M, Approved

#3005 5911 tm 5914 tm delete at grade in category 2
  src/Components/AdministratorPage/bidAudit/BidAuditCategoryCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGradeCard.jsx
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/sass/_bidAudit.scss
Labels: size/M

#3007 forgot to push
  src/Components/AdministratorPage/bidAudit/BidAuditCategoryCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGradeCard.jsx
Labels: Approved, size/XS

#2999 [TM-5844-5873] Projected Vacancy Include and Import UI Revisions
  public/config/config.json
  public/config/config_dev.json
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/sass/_positionContent.scss
  src/sass/_positionSearch.scss
Labels: Approved, size/L

#3008 small fix
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCategoryCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGradeCard.jsx
  src/actions/bidAudit.js
  src/sass/_bidAudit.scss
Labels: size/S

#2991 TM-6076: Publishable Positions Re-Integration (Read, Filtering, Pagination)
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/sass/_positionSearch.scss
Labels: size/M, Approved

#3002 TM-6164, use display name for org, works around known FSBID issue
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
Labels: Approved, size/XS

#2997 [TM-6125] Re-Integrate Projected Vacancies Read
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/PaginationWrapper/PaginationWrapper.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/sass/_common.scss
Labels: Approved, size/L

#3009 Revert "TM-6164, use display name for org, works around known FSBID issue"
  src/Components/BureauPage/SearchPostAccess/SearchPostAccess.jsx
Labels: size/XS

#3010 PV Fixes
  public/config/config.json
  public/config/config_dev.json
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/actions/assignment.js
Labels: size/M, Approved

#3014 TM-6123, TM-6126, Re-Interate Projected Vacancy
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/actions/projectedVacancy.js
  src/sass/_positionContent.scss
Labels: Approved, size/L

#3015 Projected Vacancy Updated New Fields
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
Labels: Approved, size/S

#3013 TM-6124-Projected-Vacancies-UI
  src/Components/AoPage/AoPage.jsx
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Constants/Menu.js
Labels: Approved, size/S

#3016 TM-6054 lock down PPOS by perms
  src/Components/PublishablePositions/PublishablePositions.jsx
Labels: size/M

#2856 [TM-5572] Bidding Tool Integration (Edit)
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
  src/actions/biddingTool.js
  src/reducers/biddingTool/biddingTool.js
  src/reducers/biddingTool/index.js
Labels: Approved, size/L

#3017 by code for org
  src/Components/PublishablePositions/PublishablePositions.jsx
Labels: size/XS

#3019 Maintain Assignment Edit Hotfix
  src/Components/AssignmentsSeparations/Assignment/Assignment.jsx
Labels: size/XS

#3018 Pv testing bugdfix
  src/Components/AoPage/AoPage.jsx
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
Labels: size/S

#3021 Bidding Tool Hotfix
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
  src/actions/biddingTool.js
Labels: size/M

#3020 [TM-6077] Re-Integrate Publishable Positions Edit
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: size/XS

#3022 disable paginate on edit mode
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
Labels: size/XS

#3023 Publishable Positions Edit Hotfox
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: size/XS

#3025 Publishable Positions Edit Hotfix
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: size/XS

#3026 Bidding Tool Hotfix
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
  src/actions/biddingTool.js
Labels: size/XS

#3024 test fix
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
Labels: size/S

#3027 Bidding Tool Number Fields
  src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
Labels: size/XS

#3029 Release 13 Hotfix
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: size/M

#3030 Release-13-Feature-Flags
  public/config/config.json
  public/config/config_dev.json
  src/Components/PositionDetailsItem/__snapshots__/PositionDetailsItem.test.jsx.snap
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.test.js
Labels: size/M, Approved

#3033 TM-6149, update TOD in search filters
  src/reducers/filters/filters.js
Labels: size/XS
