Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-07, with the labels that each got.

#3034 TM-6302 add search flag for Critical Need
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/Ribbon/IsCritNeed/IsCritNeed.jsx
  src/Components/Ribbon/IsCritNeed/index.js
  src/Components/Ribbon/Ribbon.jsx
  src/Components/Ribbon/index.js
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.test.jsx
  src/Constants/EndpointParams.js
  src/reducers/filters/filters.js
  src/sass/_ribbon.scss
Labels: size/M

#3028 Release 13.0
  package.json
Labels: do not merge, Approved, size/XS

#3037 Projected Vacancy: Removed Language Offset
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/actions/projectedVacancy.js
  src/reducers/projectedVacancy/index.js
  src/reducers/projectedVacancy/projectedVacancy.js
Labels: Approved, size/L

#3036 [TM-6170] TM1 Notifications (Read Only)
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Assignments.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/EFM.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Header.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Memo.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/MemoHeader.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Paragraphs.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Remarks.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Routing.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Training.jsx
  src/actions/assignmentNotifications.js
  src/reducers/assignmentNotifications/assignmentNotifications.js
  src/reducers/assignmentNotifications/index.js
  src/reducers/index.js
Labels: Approved, size/XXL

#3038 HOTFIX - move cycle management to admin
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AoPage/AoPage.jsx
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
Labels: size/M

#3040 Updated endpoints
  src/actions/biddingTool.js
Labels: size/XS

#3042 Update .gitignore
  .gitignore
Labels: Approved, size/XS

#3046 PPos OnSubmit Fix
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
Labels: size/XS

#3047 Revert "Merge branch 'dev' into release/13.0"
  src/Components/ResultsCard/ResultsCard.jsx
  src/Components/Ribbon/IsCritNeed/IsCritNeed.jsx
  src/Components/Ribbon/IsCritNeed/index.js
  src/Components/Ribbon/Ribbon.jsx
  src/Components/Ribbon/index.js
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.test.jsx
  src/Constants/EndpointParams.js
  src/reducers/filters/filters.js
  src/sass/_ribbon.scss
Labels: size/M

#3045 Fix/positionmanagementbureau
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/BureauPage/PositionManager/PositionManager.test.jsx
  src/Components/PostPage/PostPage.jsx
Labels: size/L

#3049 Revert "Fix/positionmanagementbureau"
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/PositionManager/PositionManager.jsx
  src/Components/BureauPage/PositionManager/PositionManager.test.jsx
  src/Components/PostPage/PostPage.jsx
Labels: size/L

#3050 Fix local jwt issue
  src/index.jsx
Labels: Approved, size/XS

#3052 Publishable Positions: Hide Classification Tab for Post Users
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
Labels: size/XS

#3058 PPos Position Classifications: Restrict Edit to Superuser
  src/Components/PublishablePositionCard/PositionClassification/PositionClassification.jsx
Labels: Approved, size/XS

#3059 Feature Flag: Publishable Positions
  public/config/config.json
  public/config/config_dev.json
  src/Constants/Menu.js
Labels: Approved, size/S

#3063 TM-6152 search on remarks
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/actions/panelMeetings.js
  src/sass/_panelSearch.scss
  src/sass/_remarks.scss
Labels: size/M, Approved

#3060 [TM-6335] TM1 Notification - Rebuild Actions
  src/Components/AssignmentsSeparations/Assignment/Assignment.jsx
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Assignments.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/EFM.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Header.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Paragraphs.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Remarks.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Routing.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Training.jsx
  src/Constants/SystemMessages.js
  src/actions/assignmentNotifications.js
  src/sass/_common.scss
  src/sass/_notificationCard.scss
Labels: size/L

#3061 [TM-6334] TM1 Notification - Preview Card
  src/Components/AssignmentsSeparations/AssignmentNotification/AssignmentNotification.jsx
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/sass/_notificationCard.scss
Labels: size/M, Approved

#3062 Merge release13 to dev
  public/config/config.json
  public/config/config_dev.json
  src/Components/AdministratorPage/AdministratorPage.jsx
  src/Components/AoPage/AoPage.jsx
  src/Components/BureauPage/BureauPage.jsx
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/PublishablePositionCard/PositionClassification/PositionClassification.jsx
  src/Components/PublishablePositionCard/PublishablePositionCard.jsx
  src/Components/PublishablePositions/PublishablePositions.jsx
  src/Constants/Menu.js
  src/actions/biddingTool.js
  src/actions/projectedVacancy.js
  src/reducers/projectedVacancy/index.js
  src/reducers/projectedVacancy/projectedVacancy.js
Labels: Approved, size/XL
