Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-09, with the labels that each got.

#3097 Employee Name Hyperlink
  src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
Labels: Approved, size/XS

#3096 Tm 6433 re work panel meeting agendas page
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingMessage.jsx
  src/Components/Agenda/AgendaItemRow/AgendaItemRow.jsx
  src/Components/AoPage/AoPage.jsx
  src/Components/CdoPage/CdoPage.jsx
  src/Components/Panel/Constants.js
  src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
  src/Components/Panel/PanelMeetingAgendas/PrintPanelMeetingAgendas.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
  src/Components/Panel/PanelMeetingSearchRow/PanelMeetingSearchRow.jsx
  src/actions/panelMeetingAgendas.js
  src/sass/_agendaItemRow.scss
  src/sass/_panelMeetingAgendas.scss
Labels: do not merge, Approved, size/XL

#3095 TM-6509-CDO-Dropdown-UI
  src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
  src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
  src/Constants/SystemMessages.js
  src/actions/bidderPortfolio.js
Labels: size/M, Approved

#3100 TM-6521-RWA-DETO-Filtering
  src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
  src/Constants/EndpointParams.js
  src/reducers/filters/filters.js
Labels: Approved, size/XS

#3102 TM-6583-CDO-UI
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Constants/Sort.js
Labels: size/M, Approved

#3101 TM-5228-Unassigned-Bidders-UI
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Constants/Sort.js
  src/Containers/BidderPortfolio/BidderPortfolio.jsx
  src/actions/bidderPortfolio.js
  src/reducers/bidderPortfolio/bidderPortfolio.js
Labels: Approved, size/L

#3103 TM-6585-CDOD30-Access
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
  src/Components/BidderPortfolio/BidControls/BidCyclePicker/BidCyclePicker.jsx
  src/Components/BidderPortfolio/BidControls/BidCyclePicker/BidCyclePicker.test.jsx
  src/Components/BidderPortfolio/BidControls/BidCyclePicker/__snapshots__/BidCyclePicker.test.jsx.snap
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx
  src/Components/BidderPortfolio/BidderPortfolioPage/__snapshots__/BidderPortfolioPage.test.jsx.snap
  src/Containers/BidderPortfolio/BidderPortfolio.jsx
  src/actions/bidderPortfolio.js
  src/reducers/bidderPortfolio/bidderPortfolio.js
  src/reducers/bidderPortfolio/index.js
Labels: Approved, size/L

#3104 restricts cdo to one choice
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
  src/Components/BidderPortfolio/BidControls/__snapshots__/BidControls.test.jsx.snap
  src/Components/BidderPortfolio/CDOAutoSuggest/CDOAutoSuggest.jsx
  src/Components/BidderPortfolio/CDOAutoSuggest/__snapshots__/CDOAutoSuggest.test.jsx.snap
Labels: Approved, size/XS

#3107 Hide-Unassigned-Bidders
  src/Components/BidderPortfolio/BidControls/BidControls.jsx
Labels: Approved, size/XS

#3098 [TM-6362] TM1 Note Save/Send
  public/config/config.json
  src/Components/AssignmentsSeparations/NotificationCard/Common/InputActions.jsx
  src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Assignments.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/EFM.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Header.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/MemoHeader.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Paragraphs.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Remarks.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Routing.jsx
  src/Components/AssignmentsSeparations/NotificationCard/Tabs/Training.jsx
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/SystemMessages.js
  src/actions/assignmentNotifications.js
  src/reducers/assignmentNotifications/assignmentNotifications.js
  src/reducers/assignmentNotifications/index.js
  src/sass/_notificationCard.scss
Labels: Approved, size/XXL

#3099 [TM-6417] TM1 Notification/Memo CDO
  src/Components/CdoPage/CdoPage.jsx
  src/Components/ProfileDashboard/Assignments/AssignmentsList.jsx
  src/Components/ProfileDashboard/Assignments/__snapshots__/AssignmentsList.test.jsx.snap
  src/Components/ProfileDashboard/ProfileDashboard.jsx
  src/Containers/ProfilePublic/ProfilePublic.jsx
Labels: size/XS

#3109 Tm 6489 export the maintain entry level page UI
  src/Components/EntryLevelPage/MaintainELPositions/MaintainELPositions.jsx
  src/Components/EntryLevelPage/MaintainELPositionsTable/MaintainELPositionsTable.jsx
  src/actions/entryLevel.js
Labels: Approved, size/S
