Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-05, with the labels that each got.

#2961 [TM-5975] Projected Vacancy Bugs
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
Labels: Approved, size/XS

#2969 TM-5974-Agenda-Item-Delete-UI
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Constants/SystemMessages.js
  src/actions/agendaItemMaintenancePane.js
  src/reducers/agendaItemMaintenancePane/agendaItemMaintenancePane.js
  src/sass/_agendaItemMaintenance.scss
Labels: size/M, Approved, Approved Pending Feedback

#2959 TM-5960: Panel Administrator Role
  public/config/config.json
  public/config/config_dev.json
  public/login.html
  src/Components/ProfileMenu/ProfileMenuCollapsed/__snapshots__/ProfileMenuCollapsed.test.jsx.snap
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Constants/Menu.js
Labels: Approved, size/XL

#2966 [TM-5976-5977] Maintain Separations/Assignments Integration and Refactor
  src/Components/AssignmentsSeparations/Assignment/Assignment.jsx
  src/Components/AssignmentsSeparations/AssignmentsSeparations.jsx
  src/Components/AssignmentsSeparations/Separation/Separation.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/Components/ReactModal/ReactModal.jsx
  src/Components/TMDatePicker/TMDatePicker.jsx
  src/actions/assignment.js
  src/reducers/assignment/assignment.js
  src/reducers/assignment/index.js
  src/sass/_assignments.scss
  src/sass/_common.scss
  src/sass/_modal.scss
Labels: Approved, size/XXL

#2973 handles if no user_info property
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
Labels: Approved, size/XS

#2974 TM-5876, Create New Bid Audit
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditModal.jsx
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
  src/sass/_bidAudit.scss
Labels: Approved, size/XL

#2970 TM-5878, Update Bid Audit
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
Labels: size/M, Approved

#2971 TM-5671, Edit Cycle Position Details
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Constants/SystemMessages.js
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
  src/sass/_datePicker.scss
  src/sass/_positionContent.scss
Labels: Approved, size/XL

#2975 taking fallback into account
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
Labels: Approved, size/XS

#2976 bid audit touchups
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditModal.jsx
Labels: Approved, size/XS

#2977 cycle position edit touchups
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
Labels: Approved, size/S

#2979 TM-5944-Updating-Regex
  src/actions/agendaItemMaintenancePane.js
Labels: Approved, size/XS

#2980 make sure editable fields are showing most current data
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
Labels: Approved, size/XS

#2983 TM-5974-Agenda-Item
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
Labels: Approved, size/XS

#2984 TM-9574
  src/actions/agendaItemMaintenancePane.js
Labels: Approved, size/XS

#2978 [TM-5896] Maintain Separation Hotfixes
  src/Components/AssignmentsSeparations/Assignment/Assignment.jsx
  src/Components/AssignmentsSeparations/AssignmentsSeparations.jsx
  src/Components/AssignmentsSeparations/Separation/Separation.jsx
  src/Constants/SystemMessages.js
  src/actions/assignment.js
  src/sass/_assignments.scss
Labels: size/M, Approved

#2981 Bid Audit Standardization/Refactor/Styling
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditModal.jsx
  src/Components/AssignmentsSeparations/AssignmentsSeparations.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
  src/sass/_assignments.scss
  src/sass/_bidAudit.scss
  src/sass/_modal.scss
  src/sass/_positionContent.scss
Labels: Approved, size/XL

#2982 [TM-5984] Maintain Assignments Remediation
  src/Components/AssignmentsSeparations/Assignment/Assignment.jsx
Labels: size/M, Approved

#2985 [TM-5961] Deconflict FSBID and Panel Admin Features
  src/Components/AdministratorPage/PanelAdmin/PanelAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PanelMeetingAdmin.jsx
  src/Components/AdministratorPage/PanelAdmin/PostPanelProcessing.jsx
  src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
Labels: Approved, size/L

#2988 TM-5912, TM-5877, Bid Audit - Create In Category & At Grade
  src/Components/AdministratorPage/bidAudit/BidAuditCategory.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCategoryModal.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGrade.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGradeModal.jsx
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
  src/sass/_bidAudit.scss
Labels: size/XL

#2986 TM-5916, TM-5915 - In Category & At Grade Bid Audit Pages
  src/Components/AdministratorPage/bidAudit/BidAudit.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCategory.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCategoryCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditCategoryModal.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGrade.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGradeCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditGradeModal.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditModal.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditSections/BidAuditSections.jsx
  src/Constants/SystemMessages.js
  src/actions/bidAudit.js
  src/reducers/bidAudit/bidAudit.js
  src/reducers/bidAudit/index.js
  src/sass/_bidAudit.scss
Labels: Approved, size/XXL

#2989 [TM-5984] Maintain Assignment/Separation Remediation
  src/Components/AssignmentsSeparations/Assignment/Assignment.jsx
  src/Components/AssignmentsSeparations/AssignmentsSeparations.jsx
  src/Components/AssignmentsSeparations/Separation/Separation.jsx
Labels: size/M, Approved

#2990 panel admin page
  src/Components/PanelAdministratorPage/PanelAdministratorPage.jsx
  src/Components/PanelAdministratorPage/PanelAdministratorPage.test.jsx
  src/Components/PanelAdministratorPage/PanelAdministratorPageLoadable.jsx
  src/Components/PanelAdministratorPage/index.js
  src/Components/ProfileMenu/ProfileMenuExpanded/__snapshots__/ProfileMenuExpanded.test.jsx.snap
  src/Components/ProfilePage/ProfilePage.jsx
  src/Constants/Menu.js
  src/Containers/PanelAdministrator/PanelAdministrator.jsx
  src/Containers/PanelAdministrator/PanelAdministrator.test.jsx
  src/Containers/PanelAdministrator/index.js
Labels: size/M
