Repository MetaPhase-Consulting/State-TalentMAP, pull requests merged in 2024-03, with the labels that each got.

#2889 AIM Legs CSS
  src/Components/Agenda/AIMLegsFormEdit/AIMLegsFormEdit.jsx
  src/Components/Agenda/AIMLegsFormEdit/AIMLegsFormEdit.test.jsx
  src/Components/Agenda/AIMLegsFormEdit/__snapshots__/AIMLegsFormEdit.test.jsx.snap
  src/Components/Agenda/AIMLegsFormEdit/index.js
  src/Components/Agenda/AIMLegsFormRead/AIMLegsFormRead.jsx
  src/Components/Agenda/AIMLegsFormRead/AIMLegsFormRead.test.jsx
  src/Components/Agenda/AIMLegsFormRead/__snapshots__/AIMLegsFormRead.test.jsx.snap
  src/Components/Agenda/AIMLegsFormRead/index.js
  src/Components/Agenda/AgendaItemLegs/AgendaItemLegs.jsx
  src/Components/Agenda/AgendaItemLegsForm/index.js
  src/Components/Agenda/AgendaItemLegsFormReadOnly/index.js
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLeg/index.js
  src/Components/Agenda/AgendaLegFormEdit/AgendaLegFormEdit.jsx
  src/Components/Agenda/AgendaLegFormEdit/AgendaLegFormEdit.test.jsx
  src/Components/Agenda/AgendaLegFormEdit/MonthYearDropdown.jsx
  src/Components/Agenda/AgendaLegFormEdit/TodModal.jsx
  src/Components/Agenda/AgendaLegFormEdit/__snapshots__/AgendaLegFormEdit.test.jsx.snap
  src/Components/Agenda/AgendaLegFormEdit/index.js
  src/sass/_AIMLegsFormEdit.scss
  src/sass/_AIMLegsFormRead.scss
  src/sass/_agendaItemLegsForm.scss
  src/sass/_agendaItemLegsFormReadOnly.scss
  src/sass/_agendaItemMaintenance.scss
  src/sass/_agendaItemRow.scss
  src/sass/_variables.scss
  src/sass/styles.scss
Labels: size/XL

#2885 TM-5412, Edit Assignment Cycles
  src/Components/AoPage/AoPage.jsx
  src/Components/BureauPage/BureauPage.jsx
  src/Components/CycleManagement/AssignmentCycleEdit.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/CycleSearchCard.jsx
  src/Components/CycleManagement/NewAssignmentCycle.jsx
  src/Components/CycleManagement/index.js
  src/Constants/SystemMessages.js
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
  src/sass/_positionSearch.scss
Labels: Approved, size/XXL

#2891 TM-5594: Default Action for Agenda Legs
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
  src/Components/Agenda/AgendaLegFormEdit/AgendaLegFormEdit.jsx
  src/Components/Agenda/AgendaLegFormEdit/__snapshots__/AgendaLegFormEdit.test.jsx.snap
Labels: dual merge, Approved, size/S

#2890 [TM-5567] AI Employee Profile Preview Tab
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.test.jsx
  src/Components/Agenda/AgendaItemMaintenancePane/__snapshots__/AgendaItemMaintenancePane.test.jsx.snap
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/sass/_agendaItemMaintenance.scss
Labels: Approved, size/L

#2898 5412 tm edit cycle cleanup
  src/Components/CycleManagement/AssignmentCycleEdit.jsx
  src/Components/CycleManagement/NewAssignmentCycle.jsx
Labels: Approved, size/XS

#2897 [TM-5691] Handling Legacy Values for Action and Travel
  src/Components/Agenda/AgendaLegFormEdit/AgendaLegFormEdit.jsx
  src/Components/Agenda/AgendaLegFormEdit/__snapshots__/AgendaLegFormEdit.test.jsx.snap
Labels: size/M, Approved

#2894 [TM-5599-5656] Projected Vacancy Integration Remediation
  src/Components/BureauPage/ProjectedVacancy/ProjectedVacancy.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
  src/Components/ProjectedVacancyCard/ProjectedVacancyCard.test.jsx
  src/Constants/SystemMessages.js
  src/actions/projectedVacancy.js
  src/reducers/projectedVacancy/index.js
  src/reducers/projectedVacancy/projectedVacancy.js
  src/sass/_datePicker.scss
Labels: Approved, size/XL

#2904 Update/tod default
  src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
Labels: size/XS

#2905 hello old friend
  src/Components/Agenda/AgendaLegFormEdit/AgendaLegFormEdit.jsx
  src/Components/Agenda/AgendaLegFormEdit/__snapshots__/AgendaLegFormEdit.test.jsx.snap
Labels: size/XS

#2902 [TM-5567] AI Employee Profile Preview Hotfix
  src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
  src/Components/Agenda/AgendaItemResearchPane/AgendaItemResearchPane.jsx
  src/hooks.js
Labels: Approved, size/S

#2901 TM-5587: Manage EL Position Filtering
  src/Components/AdministratorPage/ManageEntryLevel/EntryLevelCard.jsx
  src/Components/AdministratorPage/ManageEntryLevel/ManageEntryLevel.jsx
  src/actions/entryLevel.js
  src/sass/_spinner.scss
Labels: size/M, Approved

#2908 Fix naming
  src/Components/Agenda/AgendaLegFormEdit/AgendaLegFormEdit.jsx
Labels: Approved, size/XS

#2907 [TM-5711] AI Page Error Fix
  src/Components/Agenda/AgendaItemMaintenancePane/AgendaItemMaintenancePane.jsx
Labels: Approved, size/XS

#2913 adding documentation
  src/Components/SkillCodeList/SkillCodeList.jsx
Labels: Approved, size/XS

#2892 TM-5645, Cycle Positions Fetch
  src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
  src/Components/CyclePositionCard/CyclePositionCard.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
Labels: Approved, size/XL

#2918 TM-5703, Assignment Cycle Edit Business Rules
  src/Components/CycleManagement/AssignmentCycleEdit.jsx
Labels: size/M, Approved

#2910 TM-5676-Bid-Audit-UI
  src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
  src/Components/AdministratorPage/bidAudit/BidAuditSections/BidAuditSections.jsx
  src/Components/PositionExpandableContent/PositionExpandableContent.jsx
  src/sass/_bidAudit.scss
  src/sass/_positionContent.scss
Labels: size/S

#2924 TM-5777, Merge Assignment Cycles
  src/Components/CycleManagement/AssignmentCycleEdit.jsx
  src/Components/CycleManagement/CycleManagement.jsx
  src/Components/CycleManagement/MergeAssignmentCycles.jsx
  src/Constants/SystemMessages.js
  src/actions/cycleManagement.js
  src/reducers/cycleManagement/cycleManagement.js
  src/reducers/cycleManagement/index.js
  src/sass/_common.scss
  src/sass/_positionSearch.scss
Labels: Approved, size/L

#2912 [TM-5669] Cycle Job Category Read Integration
  src/Components/AdministratorPage/CycleJobCategories/CycleJobCategories.jsx
  src/actions/cycleJobCategories.js
  src/reducers/cycleJobCategories/cycleJobCategories.js
  src/reducers/cycleJobCategories/index.js
Labels: Approved, size/XL, Changes Requested

#2921 [TM-5670] Cycle Job Category Edit Integration
  src/Components/AdministratorPage/CycleJobCategories/CycleJobCategories.jsx
  src/actions/cycleJobCategories.js
  src/reducers/cycleJobCategories/cycleJobCategories.js
  src/reducers/cycleJobCategories/index.js
Labels: size/M, Approved
